### ISSUE TITLE
Are there going to be more "proper" (tagged) releases?

### ISSUE THREAD

**Issue by hillu** [google/gopacket#102]
Hi,

with more than half a year with fairly active development since version 1.1.10 was released, I am curious: Will there be tagged releases (with some expectation of stability) in the future of `gopacket´ or do you expect users to take whatever is current on the master branch?

Cheers,
-Hilko

**Comment by gconnell** [comment]
I'm happy to tag releases.  Not sure if anyone actually used them, but if
you like them I'm happy to use them :)

**Comment by hillu** [comment]
I'd be equally happy to switch the [Debian package](https://tracker.debian.org/pkg/gopacket) (which so far has been tracking the tagged releases) to more or less regular snapshots -- whatever works best from your point of view.

Thank you for a great library BTW.

**Comment by gconnell** [comment]
I'll go back to tagging releases regularly.  If you notice a long lag
between the last tag, feel free to ping this list and I'll add a newer one.

**Comment by dabdine-r7** [comment]
ping for a new release

**Comment by gconnell** [comment]
God I'm bad at this.  v1.1.12 pushed.
