### ISSUE TITLE
pfring can't be used, make failed.

### ISSUE THREAD

**Issue by gao114882** [google/gopacket#1020]
![企业微信截图_1654082269883](https://user-images.githubusercontent.com/22283924/171392380-fb406f54-886f-4642-97f3-3fef42cf999a.png)

the error is : 
# github.com/google/gopacket/pfring
./pfring.go:14:20: fatal error: pfring.h: No such file or directory
 #include <pfring.h>

**Comment by mcoops** [comment]
First question, as `gopacket/pfring` is just using c bindings to the library, I assume you've installed pfring from ntop?
