### ISSUE TITLE
AF_PACKET: need to expose network interface from which packet was captured

### ISSUE THREAD

**Issue by rshriram** [google/gopacket#104]
Context: Host with several docker containers
Capture mode: AF_PACKET, all interfaces [i.e., bound to pseudo interface, capturing packets from all interfaces]

When running gopacket based app on a machine with multiple docker containers, its often essential to identify the interface from which the packet was captured, so that it can be tied back to the target container. Looking at the metadata information (or even the ethernet layer code), the network interface information is not exposed.

In the absence of this information, it is necessary to run the packet capture process on each virtual interface, which is highly inefficient. (https://groups.google.com/forum/m/#!topic/linux.kernel/3T8aWc_gLCc)

With AF_PACKET, its possible to monitor packets arriving on all interfaces using ifindex 0, and after the packet arrives at the userpspace, its possible to identify the specific interface using the sockaddr_ll.
Exposing this information in either the metadata or as part of some layer would be very helpful.

**Comment by LrsK** [comment]
I think this is possible by looking at the sockaddr_ll section of the tpacket frame. 
In https://www.kernel.org/doc/Documentation/networking/packet_mmap.txt it says:

```
   Frame structure:
   - Start. Frame must be aligned to TPACKET_ALIGNMENT=16
   - struct tpacket_hdr
   - pad to TPACKET_ALIGNMENT=16
   - struct sockaddr_ll
   - Gap, chosen so that packet data (Start+tp_net) aligns to TPACKET_ALIGNMENT=16
   - Start+tp_mac: [ Optional MAC header ]
   - Start+tp_net: Packet data, aligned to TPACKET_ALIGNMENT=16.
   - Pad to align to TPACKET_ALIGNMENT=16
```

The sockaddr.ll section could perhaps be extracted by performing:

```
// For V3 headers
var ll *C.struct_sockaddr_ll
//     Start at w.packet                           +  aligned size of w.packet
d := uintptr(unsafe.Pointer(w.packet)) + uintptr(tpacketAlign(int(unsafe.Sizeof(w.packet))))
ll = (*C.struct_sockaddr_ll)(unsafe.Pointer(&d))
```

sockaddr_ll.sll_ifindex will give the index of the interface, which can be mapped to a string at init-time by using ioctl with SIOCGIFNAME.

**Comment by gconnell** [comment]
I believe this is now done.
