### ISSUE TITLE
Variable PacketSource buffer size

### ISSUE THREAD

**Issue by LrsK** [google/gopacket#143]
It would be convenient if the buffer size of the channel of Packets was adjustable, so that it would look like this:

```
func (p *PacketSource) Packets(chanSize uint) chan Packet {
	if p.c == nil {
		p.c = make(chan Packet, chanSize)
		go p.packetsToChannel()
	}
	return p.c
}
```

For some applications, the buffer will need to be quite large to accommodate large amounts of traffic.

**Comment by gconnell** [comment]
Could this be handled with:

myChan := make(chan Packet, N)
go func() {
  for p := range psource.Packets() {
    myChan <- p
  }
}()

**Comment by LrsK** [comment]
Good idea. Thanks!
