### ISSUE TITLE
go build can not successfully buld

### ISSUE THREAD

**Issue by cklonger** [google/gopacket#149]
command line log 

# github.com/google/gopacket/afpacket
could not determine kind of name for C.PACKET_FANOUT

seems there is an import error of "C"

my os is centos 6.7 x64

**Comment by rufoa** [comment]
You're probably missing the headers for your kernel - do `yum install kernel-devel`

**Comment by rufoa** [comment]
PACKET_FANOUT requires kernel >= 3.1

**Comment by gconnell** [comment]
Closing.
