### ISSUE TITLE
pcap tests failing on Windows

### ISSUE THREAD

**Issue by ligustah** [google/gopacket#159]
Hi,

I tried to use the OpenOffline function to parse a file, but a simple test program would always crash. When running the tests in the pcap package I would get the same crash, so I guess it's a general problem with my system configuration (running Windows 10).

```
D:\Dropbox\Go-Projects\src\github.com\google\gopacket\pcap>go version
go version go1.5.2 windows/amd64

D:\Dropbox\Go-Projects\src\github.com\google\gopacket\pcap>go test
Exception 0xc0000005 0x0 0x1625ffe 0x859810
PC=0x859810
signal arrived during external code execution

github.com/google/gopacket/pcap._Cfunc_pcap_open_offline(0x1561f90, 0x15671b0, 0x0)
        ??:0 +0x3d
github.com/google/gopacket/pcap.OpenOffline(0x708af0, 0x12, 0x0, 0x0, 0x0)
        D:/Dropbox/Go-Projects/src/github.com/google/gopacket/pcap/pcap.go:236 +0x106
github.com/google/gopacket/pcap.TestPcapFileRead(0xc083210000)
        D:/Dropbox/Go-Projects/src/github.com/google/gopacket/pcap/pcap_test.go:54 +0x547
testing.tRunner(0xc083210000, 0x870080)
        c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
        c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0x74a6b0, 0x870080, 0x4, 0x4, 0x410401)
        c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc082481ef8, 0x0)
        c:/go/src/testing/testing.go:494 +0x77
main.main()
        github.com/google/gopacket/pcap/_test/_testmain.go:62 +0x11d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1721 +0x1
rax     0xc083221fb0
rbx     0xc083221b00
rcx     0x1561f90
rdi     0xc083221b00
rsi     0xc083221fb0
rbp     0x0
rsp     0xfdfd78
r8      0xc082476300
r9      0xc083221a98
r10     0x0
r11     0x0
r12     0x6
r13     0x7463ee
r14     0x3
r15     0x8
rip     0x859810
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
exit status 2
FAIL    github.com/google/gopacket/pcap 0.249s

D:\Dropbox\Go-Projects\src\github.com\google\gopacket\pcap>
```

I grabbed the pcap files here: https://www.winpcap.org/devel.htm and put them into C:\WpdPack. Is this a known problem or is there a way I could get a more helpful error message?

**Comment by rezen** [comment]
I had issues with Windows as well. This answer helped me http://stackoverflow.com/questions/38047858/compile-gopacket-on-windows-64bit

**Comment by ligustah** [comment]
I actually started looking at it again just yesterday! After I managed to get it compiled and running on Win7 I gave it another shot on Win10 last night, but to no avail. I will definitely try your suggestion.

**Comment by ligustah** [comment]
@rezen wow, this actually worked! Thanks a lot.
If only I could remember what I wanted to do with it 😕

**Comment by gconnell** [comment]
Hmm, not sure how best to handle this from gopacket's side of things.  Is there a particular place in the documentation where we should link to this stackoverflow answer?

**Comment by gconnell** [comment]
Added note in https://github.com/google/gopacket/commit/02b1b44a6dc7fe2d7b44394c6fd2c48a1761e95a

**Comment by ligustah** [comment]
@gconnell looks like a good place for the link, thanks!
