### ISSUE TITLE
packetsToChannel() should propogate error codes

### ISSUE THREAD

**Issue by barclayo** [google/gopacket#163]
packetsToChannel() explicitly ignores errors from NextPacket(), on Windows this manifests with the following behavior:  if the device is reading via a live interfaces, and the device sleeps then wakes, any reads on the previously open handle will result in a ReadError.  Since this is distinct from io.EOF, the binary will spin within Packets() and eat a full core.

Workaround:  write your own Packets() convenience routine and handle read errors as appropriate.

**Comment by notti** [comment]
I'm not completely sure what the reason was for ignoring all errors except io.EOF. Maybe it would be best to special handle the exact error that would happen.

**Comment by notti** [comment]
Maybe fixed by #625 
If there is an error we overlooked, it simply can be added to the list now.
