### ISSUE TITLE
pcapgo should perform bounds checking on packet sizes

### ISSUE THREAD

**Issue by david415** [google/gopacket#171]
Dear gopacket developers,

While reviewing gopacket source code for #167 I noticed that pcapgo has essentially the same problem here:

https://github.com/google/gopacket/blob/master/pcapgo/read.go#L104

``ci.CaptureLength`` is not guaranteed to be smaller than the buffer length therefore a pcap file containing a ``CaptureLength`` longer than the ``snaplen`` can cause this code the panic. Correct?

I have not bothered to fix this yet. Shall I submit a pull request?

**Comment by lhausermann** [comment]
Hi,
Yes you are right on this. We should add a check while reading headers and/or packetdata.

**Comment by david415** [comment]
here's my first attempt at fixing this:
https://github.com/google/gopacket/pull/177
