### ISSUE TITLE
SSL/TLS Layer

### ISSUE THREAD

**Issue by swsnider** [google/gopacket#187]
Is there any plan to provide a SSL/TLS layer that provides version information + interprets Client/Server HELLOs and Certificates?

Is this already available elsewhere?

**Comment by gconnell** [comment]
Since SSL/TLS is wrapped inside a TCP session and thus isn't per-packet, no current plans.  However, using tcpassembly/tcpreader, pulling out the SSL handshake shouldn't be too horrible a task.

**Comment by lhausermann** [comment]
Just wanted to mention that we are still comitted to make https://github.com/google/gopacket/pull/116 go further. We do not have many time to fix the comments, and submit a new PR... but it will come soon I hope. 

Once we (as a GoPacket community) have a better TCP assembly package, it will be easier to implement a SSL layer or as @gconnell suggested to plug standard lib ssl package.

What is your targeted usage ?

**Comment by bradleyfalzon** [comment]
I have some private (not ready for public) code that disassembles a client hello (captured via gopacket.pcap into a gopacket.Packet) payload into:

```
type ClientHello struct {
    TLSMessage
    HandshakeType    uint8
    HandshakeLen     uint32
    HandshakeVersion Version
    Random           []byte
    SessionIDLen     uint32
    SessionID        []byte
    CipherSuiteLen   uint16
    CipherSuites     []CipherSuite
    CompressMethods  []uint8
    ExtensionLen     uint16
    Extensions       map[Extension]uint16 // [Type]Length
    SNI              string
    SignatureAlgs    []uint16
    SupportedGroups  []uint16
    SupportedPoints  []uint8
    OSCP             bool
    ALPNs            []string
}
```

I'd like to complete this work, but haven't had time.

**Comment by tomatopeel** [comment]
@bradleyfalzon I'd be interested to take a look. I have a need to analyze some HTTP traffic which is currently TLS encrypted.

**Comment by bradleyfalzon** [comment]
Sorry for the delay, it's not quite up to scratch, but I've made it available here: https://github.com/bradleyfalzon/tlsx

**Comment by lhausermann** [comment]
Thanks Bradley. Can you add a license so we would reuse this a TLS layer in gopacket? Same as gopacket would be great!

**Comment by bradleyfalzon** [comment]
Add one? It has BSD 2-Clause currently https://github.com/bradleyfalzon/tlsx/blob/master/LICENSE, what do you mean by add?

**Comment by bradleyfalzon** [comment]
and honestly, it's not the best Go out there, it was very early on when I wrote it.

**Comment by lhausermann** [comment]
Oops I was just looking at the code itself. That's fine.
