### ISSUE TITLE
Connections that never had a SYN only get their data via Flush*

### ISSUE THREAD

**Issue by gabrielrussell** [google/gopacket#192]
Connections that never had a SYN never set conn.nextSeq. This means that AssembleWithTimestamp never calls sendToConnection. sentToConnection only gets called via Flush*

This makes it impossible to get a lower latency stream of data from this sort of connection. Data is only provided when periodic flushes are called.

I'd like to be able to tell a connection to go ahead and set nextSeq

It seams to me that the best way to do this would be in FlushOlderThan, when packets older then t are flushed, on a connection without a nextSeq, to set it to the seq of the next packet. This would be controlled by a new AssemblerOption bool.

**Comment by lhausermann** [comment]
Hi. Would you please try the new TCP tracker that @sentryo contributed?

**Comment by gabrielrussell** [comment]
@lhausermann, yea, that looks to be a fix for the problem that I was having. Thanks for the heads up.
