### ISSUE TITLE
Reading http response from an http request

### ISSUE THREAD

**Issue by amirhev** [google/gopacket#202]
Is it possible to read the http response from a specific http request ?
I've tried reading the response using the http.ReadResponse(buf,request) but it is always nil

**Comment by lhausermann** [comment]
Hi @amirhev 

Can you copy/paste the snippet of code you used?

Laurent

**Comment by amirhev** [comment]
Sure,
`var handle *pcap.Handle
handle, err = pcap.OpenLive(*iface, int32(*snaplen), true, pcap.BlockForever)
// Set up assembly
streamFactory := &httpStreamFactory{}
streamPool := tcpassembly.NewStreamPool(streamFactory)
assembler := tcpassembly.NewAssembler(streamPool)
packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
packets := packetSource.Packets()
ticker := time.Tick(time.Minute)
for {
	select {
	case packet := <-packets:
	// A nil packet indicates the end of a pcap file.
	if packet == nil {
	return
	}
if *logAllPackets {
	log.Println(packet)
}
if packet.NetworkLayer() == nil || packet.TransportLayer() == nil || packet.TransportLayer().LayerType() != layers.LayerTypeTCP {
	log.Println("Unusable packet")
	continue
}
for packet := range packetSource.Packets() {
	
	if event, filtered := Filter(packet); !filtered {
	fmt.Println(event)
	}
}
func Filter(packet gopacket.Packet) (Event, bool) {
	appLayer := packet.ApplicationLayer()
	
	//if appLayer != nil && strings.Contains(string(appLayer.Payload()), "HTTP") {
	if appLayer != nil {
	
	payloadReader := bytes.NewReader(appLayer.Payload())
	bufferedPayloadReader := bufio.NewReader(payloadReader)
	
	request, err := http.ReadRequest(bufferedPayloadReader)
	response, _ := http.ReadResponse(bufferedPayloadReader, request)
	
	
	}
}`
So the request holds the request as it should and the response is always nil

**Comment by gconnell** [comment]
tcpassembly currently assembles unidirectional streams, not bidirectional, so a request doesn't have an associated response.  To make this work, one must use the Flow from the request to look up the response stream, then pull the response from it.  It's doable, but not particularly easy, unfortunately :(

**Comment by lhausermann** [comment]
Dear all , @gconnell 

We are still planning to release an updated version of bidirectional stream reassembly
An updated PR should be released but we lack some free time on

**Comment by frkn4129** [comment]
i am having the same problem. Did this happen? @lhausermann

**Comment by frkn4129** [comment]
@amirhev  are you solved this response nil problem ?

**Comment by shixiaofeia** [comment]
使用 [gopacket-http](https://github.com/shixiaofeia/gopacket-http), 即可获得拼装好的http.Request 和 http.Response
