### ISSUE TITLE
Support gzip pcap files in pcapgo/read.go

### ISSUE THREAD

**Issue by bramp** [google/gopacket#213]
Wireshark will transparently decompress a gzip pcap file. pcapgo.NewReader should check if the first couple of bytes are 0x1f 0x8b, and if so wrap the io.Reader with a gzip.NewReader.

This will allow pcapgo to open compressed pcap files, and  would be consistent with how wireshark's wiretap library does it https://github.com/wireshark/wireshark/blob/90e1232672446e79e75e5c6877310a49f23ae228/wiretap/file_wrappers.c#L575

Happy to send a pull request.

**Comment by lhausermann** [comment]
Hi Andrew
I would love to merge such pull request!
See you soon ;)
