### ISSUE TITLE
pcapgo's ReadPacketData has ZeroCopyReadPacketData semantics

### ISSUE THREAD

**Issue by mspielberg** [google/gopacket#219]
pcapgo allocates a single buffer while reading the file header of a pcap dump. Every call to ReadPacketData() overwrites this buffer, and returns a slice pointing into this buffer, so successive calls invalidate the slice returned from prior calls. This is unexpected, and makes pcapgo not a drop-in replacement for pcap.OpenOffline().

pcapgo should probably get a ReadPacketData() that populates a freshly allocated slice on each call, for compatibility, and the current method should be renamed ZeroCopyReadPacketData().

**Comment by lhausermann** [comment]
Thanks for reporting this issue.
I'd like to have the comments of @gconnell on this, as he was the original author of both packages.

**Comment by gconnell** [comment]
True, this is non-optimal.  Let me know if
https://github.com/google/gopacket/pull/221 solves this for you?

**Comment by gconnell** [comment]
Fixed.
