### ISSUE TITLE
invalid argument r.snaplen (type uint32) for len - pcapgo/read.go

### ISSUE THREAD

**Issue by mehrdadrad** [google/gopacket#225]
ReadPacketData changed and there is error at line 124 
invalid argument r.snaplen (type uint32) for len

```
if ci.CaptureLength > int(r.snaplen) {
    err = fmt.Errorf("capture length exceeds snap length: %d > %d", 16+ci.CaptureLength, len(r.snaplen))
    return
}
```

**Comment by tasdomas** [comment]
Affects me too.

**Comment by gconnell** [comment]
Fixed by
https://github.com/google/gopacket/commit/1b746f68116cb7c7ada4625eb718cf45e67dc31a

Not sure why Travis didn't catch this in the initial commit.  Sorry about
that.
