### ISSUE TITLE
Handle.SetBPFFilter is not thread safe across multiple handles

### ISSUE THREAD

**Issue by paul-pearce** [google/gopacket#226]
Running  go1.5.2 linux/amd64 under ubuntu 14.04 with gopacket c4d647984d4671d9dd91770dae77923a0b48b389

The following sample code will cause various forms of memory corruption and general overall sadness.

```
package main

import (
    "time"
    "fmt"
    "sync"
    "github.com/google/gopacket/pcap"
)

var mutex sync.Mutex

func doWork() {

    handle, _ := pcap.OpenLive("eth0", 96, true, -1)
    //mutex.Lock()
    handle.SetBPFFilter("src host 8.8.8.8")
    //mutex.Unlock()

    for {
        data, _, _ := handle.ReadPacketData()
        if data != nil {
            fmt.Println(data)
        }
    }
}

func main() {

    for i := 0; i < 10; i++ {
        go doWork()
    }

    time.Sleep(time.Duration(10) * time.Second)

}
```

Uncommenting the mutex locking resolves the issue.

Sample output:

> $ sudo ./main 
> *** Error in `./main': realloc(): invalid next size: 0x00007fa0900012c0 ***
> SIGABRT: abort
> PC=0x7fa097c16c37 m=9
> signal arrived during cgo execution
> 
> goroutine 55 [syscall, locked to thread]:
> runtime.cgocall(0x571d00, 0xc821283e00, 0x0)
> 	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc821283db8 sp=0xc821283d88
> github.com/google/gopacket/pcap._Cfunc_pcap_compile(0x7fa0800009f0, 0xc821160060, 0x7fa080000ea0, 0xf8ffffff00000001, 0x0)
> 	??:0 +0x39 fp=0xc821283e00 sp=0xc821283db8
> github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0xc82005a140, 0x67e990, 0x10, 0x0, 0x0, 0x0, 0x0)
> 	XXX/src/github.com/google/gopacket/pcap/pcap.go:472 +0x202 fp=0xc821283e70 sp=0xc821283e00
> github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0xc82005a140, 0x67e990, 0x10, 0x0, 0x0)
> 	XXX/src/github.com/google/gopacket/pcap/pcap.go:502 +0x77 fp=0xc821283ed8 sp=0xc821283e70
> main.doWork()
> 	XXX/main.go:16 +0x85 fp=0xc821283fb0 sp=0xc821283ed8
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc821283fb8 sp=0xc821283fb0
> created by main.main
> 	XXX/main.go:30 +0x38

**Comment by spsholleman** [comment]
Also just ran into this and experienced the "general overall sadness".

**Comment by gconnell** [comment]
Fixed in https://github.com/google/gopacket/commit/de3f5d8b78486bd45868b6a545f7113cf17b00cc and https://github.com/google/gopacket/commit/b83f94714c36e30ce851be1d5a0a5226f9f1bca4
