### ISSUE TITLE
ip header checksum calculation is wrong

### ISSUE THREAD

**Issue by nathandfox** [google/gopacket#231]
https://github.com/google/gopacket/blob/master/layers/ip4.go#L150

the current code is wrong in the case of addition of the carry

https://play.golang.org/p/z8jcO1yUC4

**Comment by nathandfox** [comment]
Submitted pull request

https://github.com/google/gopacket/pull/232

**Comment by gconnell** [comment]
I believe this issue has been fully fixed.
