### ISSUE TITLE
go packet capture losing data.

### ISSUE THREAD

**Issue by behramkhan** [google/gopacket#237]
Go packet capturing facility seems to loose data.

I have written a basic example (example code below). This example works fine if I am sending small data chunks. If I send bigger data, for example 5MB file from source to destination,  the "packet source" starts to miss data.

When I use tcpflow, I can reconstruct the data I sent every time, but the golang example misses chunks of data during reassembly.

For example when I transfer a file using netcat from source to destination I am not able to capture all the data using golang packet capture.

When I use tc command to slow down traffic, then the application works just fine. That's strange. Is there a limit to the speed at which go library can capture packets? tcpflow seems to capture all the traffic just fine.

`var iface = flag.String("i", "em1", "Interface to get packets from")
var fname = flag.String("r", "", "Filename to read from, overrides -i")
var snaplen = flag.Int("s", 65536, "SnapLen for pcap packet capture")
var filter = flag.String("f", "tcp and dst port 514", "BPF filter for pcap")
var logAllPackets = flag.Bool("v", false, "Logs every packet in great detail")

func main() {
    //defer util.Run()()
    var handle *pcap.Handle
    var err error

```
handle, err = pcap.OpenLive(*iface, int32(*snaplen), true, pcap.BlockForever)

if err != nil {
    log.Fatal(err)
}

if err := handle.SetBPFFilter(*filter); err != nil {
    log.Fatal(err)
}

fmt.Println("pcap file opened")
var snapshotLen uint32  = 65536
f, _ := os.Create("test.pcap")
w := pcapgo.NewWriter(f)
w.WriteFileHeader(snapshotLen, layers.LinkTypeEthernet)
defer f.Close()
defer handle.Close()

packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
packets := packetSource.Packets()
ticker := time.Tick(time.Minute * 4)
for {
    select {
        case packet := <-packets:
            w.WritePacket(packet.Metadata().CaptureInfo, packet.Data())

        case <-ticker:
            fmt.Println("pcap file closed")
            return

    }
}
```

}`

**Comment by gconnell** [comment]
If you TCPDump to a file, then read from the file with gopacket, does it still fail, or does it work?

Any chance your snaplen is too small (probably not, it's huge :P)

BTW, you're not actually parsing your flags anywhere, you should probably call flag.Parse().

Also, check errors coming from WriteFileHeader and WritePacket?

**Comment by gconnell** [comment]
Any update on this?

**Comment by notti** [comment]
No answer for 2 years...

**Comment by lllby1993** [comment]
I meet the same problem when I use the gopacket.
