### ISSUE TITLE
undefined: C in C.PCAP_NETMASK_UNKNOWN

### ISSUE THREAD

**Issue by mehrdadrad** [google/gopacket#244]
I'm seeing the below error at travis-ci once it tries to build myLG app w/ latest Go version but w/ Go version 1.7 it's fine.

go version devel +7ea5829

 `
The command "eval go get -t -v ./..." failed. 
github.com/google/gopacket/pcap
../../google/gopacket/pcap/pcap.go:594: undefined: C in C.PCAP_NETMASK_UNKNOWN
`

**Comment by gconnell** [comment]
Hmm, we dealt with PCAP_NETMASK_UNKNOWN before here:   https://github.com/google/gopacket/issues/14

Maybe this is a regression of some sort?

**Comment by gconnell** [comment]
Actually, that's saying that "C" itself is undefined, which is REALLY weird... there's definitely a big 'import "C"' at the top of that file.

**Comment by gconnell** [comment]
I have yet to confirm this, but if confirmed, I'd say a post to golang-nuts is probably the next logical step.  If you want to short-circuit things, feel free to do that right away.

**Comment by mehrdadrad** [comment]
I tried to post there but as I haven't posted there maybe it takes 24 hours to show up.

**Comment by andlabs** [comment]
Yes, it seems to be a regression in Go itself. Finding the faulty commit now.

**Comment by andlabs** [comment]
Regression by commit a16954b8a7d66169760fb60dd7f3d4e400a5e98c. Not sure what a simpler reproduction is, but I have an idea...

**Comment by andlabs** [comment]
Nope, can't figure out what's causing it to miscompile, sorry. But we can now report it to the Go team.

**Comment by andlabs** [comment]
And it's fixed: https://github.com/golang/go/commit/b7c7949817e5bee801dfb333f483a080fa1f29e7

**Comment by mehrdadrad** [comment]
Confirmed, Thanks!

**Comment by andlabs** [comment]
Also fwiw yes your original message did show up on the mailing list, but I guess we all just decided to silently ignore it.

**Comment by gconnell** [comment]
Have you reported, or would you like me to?  Either way works fine for me.

**Comment by andlabs** [comment]
A bit late, @gconnell; everything's been fixed now.

**Comment by gconnell** [comment]
That's weird, I sent that email 4 days ago :-/
