### ISSUE TITLE
[Need Tuturial] Using SCTP with afpacket (if it`s best)

### ISSUE THREAD

**Issue by andresKM** [google/gopacket#245]
I`m only starting to use golang and gopacket, so I may ask stupid or incorrect questions. If somebody would be so kind to correct me or tell me I make it wrong, that would be very nice.

Prerequisites: 
- I`ve read that pcap is slower than pf_ring and pf_ring is slower than af_packet.
- using SCTP to be able to "talk" with telecom servers that use SCTP (maybe ~20). So I need to read and then on certain condition send packets to make a dialog
- ability to compile and test on linux and then port/crosscompile to Windows

Questions:
- Should I use afpacket?
- Will it run on Windows then? 
- Do I need to configure my OS (Ubuntu, for example) specially to process packets faster using afpacket (sysctl tweaks/cpu affinity or tmth)?
- I read 60% of files in the repo, but I didn`t understand the best way to implement this. What functions/buffers/rings should I use? Maybe I need to disable other things apart from SCTP?

Thanks a lot!!!

**Comment by andresKM** [comment]
Anyone here?!

**Comment by lhausermann** [comment]
Dear Andres

Pfring or afring will be available only on xBSD or Linux machine. 
As you are starting I recommend to stick with the pcap interface especially if you need Windows port.

I suggest you start with examples/pcapdump to understand the high level API.

**Comment by andresKM** [comment]
Thanks!
