### ISSUE TITLE
Payload empty for DNS and DHCPv4 packets

### ISSUE THREAD

**Issue by mbward** [google/gopacket#254]
https://godoc.org/github.com/google/gopacket#hdr-Pointers_To_Known_Layers makes me think that packet.ApplicationLayer().Payload() will always return the body of the TCP or UDP packet.

This was true for DHCP until dhcpv4.go was added, but now Payload returns nil.

DNS also returns nil, but has done so for much longer.

**Comment by gconnell** [comment]
UDP/TCP are transport layers, so TransportLayer().Payload should work?

ApplicationLayers are one above, so for them I'd expect
ApplicationLayer.Contents() to do what you're asking for.  Not saying it
does, but that's what I'd expect :)

**Comment by mbward** [comment]
TransportLayer().LayerPayload() seems to do what I want.

I filed the report to see if we could reconcile the difference between the docs and behavior of Payload().

**Comment by lhausermann** [comment]
@gconnell any ideas on this one?

**Comment by gconnell** [comment]
Looking at this report, the code does what I'd expect it to.  Not saying my expectations are correct, just that the code seems to be doing what I think it should.

In effect, each layer has LayerContents (bytes for the current layer) and LayerPayload (bytes for the layer it contains).  If you're looking for UDP body, then, you'd either look for Transport.Payload or Application.Contents.  Application.Payload should generally work only in cases where an application layer has an actual payload within it.

There is a separate issue of the Payload layertype, which is a placeholder for "I have no idea what's in here", and it may have overloaded terminology that conflicts with the above.  Unfortunately, I'm not sure how best to handle that in a backwards-compatible fashion.

**Comment by lhausermann** [comment]
That's also my understanding (and why I followed that logic in the DNS layer.. ;-)

Closing it.
