### ISSUE TITLE
Gopacket cross compilation to windows and osx on linux

### ISSUE THREAD

**Issue by SergiiShapoval** [google/gopacket#255]
Hi, 
I am trying to cross-compile
http://www.devdungeon.com/content/packet-capture-injection-and-analysis-gopacket#open-device

compilation for windows (windows/amd64) returns next error:

> [exec] # runtime/cgo
> [exec] gcc: error: unrecognized command line option ‘-mthreads’

for OSX (darwin/amd64):

> [exec] # net
> [exec] could not determine kind of name for C.AI_MASK

for both, I am using CGO_ENABLED=1

do we have a HOW TO for gopacket cross-compilation?

P.S. compilation for linux was successful

**Comment by gconnell** [comment]
Hmm, not sure how to handle this... I don't think this is a gopacket
problem, since neither the strings 'mthreads' nor 'AI_MASK' show up
anywhere in its codebase.

I'm unfamiliar with cross-compilation and don't have a windows/mac to
compile with, so I'll have to defer to the community for a how-to.  Maybe
add an issue?

**Comment by SergiiShapoval** [comment]
Hi, Graeme,
thank you for the response,
do you mean to add an issue to libpcap community?

I am compiling sources on Linux by changing ENV variables GOOS and GOARCH
to windows/darwin and amd64 correspondingly (
https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5)

2016-11-14 17:24 GMT+02:00 Graeme Connell <notifications@github.com>:

**Comment by gconnell** [comment]
No, I meant an issue on the GoPacket issue tracker, to see if someone wants
to pick it up :)

**Comment by SergiiShapoval** [comment]
ok)

**Comment by krzysztofantczak** [comment]
Old thread but... Afair its compiler issue. Use MINGW.

**Comment by gconnell** [comment]
Closing this for now, feel free to reopen if it's still an issue.
