### ISSUE TITLE
SetBPFFilter not threadsafe?

### ISSUE THREAD

**Issue by danmia** [google/gopacket#258]
I have a server that's doing concurrent captures (each capture in their own goroutine) on a given node and I seem to have run into a condition where if multiple "err := handle.SetBPFFilter(req.Bpf); " are happening at the same time I run into the error below.  I see in the gopacket source code notes that point to this being handled by gopacket so I was curious if you could give any guidance into where I'm going wrong?  Is this not thread safe?  and if not, any suggestions on how to handle this case would be greatly appreciated.  I tinkered with the idea of compiling before spinning off the goroutine but I figured I'd ask first.

** Error in `Successfully compiled BPF Filter: [host 10.0.0.1]
SIGABRT: abort
PC=0x7f9eba9b95f7 m=10
signal arrived during cgo execution

goroutine 264 [syscall, locked to thread]:
runtime.cgocall(0x718f50, 0xc42116d428, 0xc400000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42116d3e0 sp=0xc42116d3a0
github.com/google/gopacket/pcap._Cfunc_pcap_compile(0x7f9e980009d0, 0xc4211ba6f0, 0x7f9e98003d50, 0x1, 0x0)
	??:0 +0x4d fp=0xc42116d428 sp=0xc42116d3e0
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0xc421ca66c0, 0xc4211e0500, 0xc, 0x0, 0x0, 0x0, 0x0)
	/home/danm/work/src/github.com/google/gopacket/pcap/pcap.go:472 +0x2d6 fp=0xc42116d4c0 sp=0xc42116d428
github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0xc421ca66c0, 0xc4211e0500, 0xc, 0x0, 0x0)
	/home/danm/work/src/github.com/google/gopacket/pcap/pcap.go:502 +0x8d fp=0xc42116d548 sp=0xc42116d4c0
main.captureToBuffer(0x0, 0x0, 0xc4211e04ea, 0x2, 0xc4224201c0, 0x2, 0x4, 0x0, 0x0, 0x0, ...)

**Comment by gconnell** [comment]
Are you sync'd past https://github.com/google/gopacket/commit/de3f5d8b78486bd45868b6a545f7113cf17b00cc and https://github.com/google/gopacket/commit/b83f94714c36e30ce851be1d5a0a5226f9f1bca4 ?

**Comment by danmia** [comment]
omg.  That was it.  I was positive I updated it.  Obviously positively wrong ;)   Sorry for the noise.
