### ISSUE TITLE
Dot11elt and wps

### ISSUE THREAD

**Issue by DeveloppSoft** [google/gopacket#261]
Hello,
I wonder how can I access the dot11elt infos of a packet in order to retrieve some wps infos?
Thanks.

**Comment by lhausermann** [comment]
Hi. Looking at your request : I assume that you would have to build upon Dot11 layer in Gopacket and extend it to get access to WPS info. 
https://github.com/devttys0/wps/blob/master/wpstools/wpscan.py gives you some ideas and guidance.
I'll be happy to review your patch.

**Comment by DeveloppSoft** [comment]
Hey, yep, I am working on it.
Thanks for the help.
