### ISSUE TITLE
opensbd: cannot use C.time_t

### ISSUE THREAD

**Issue by jungle-boogie** [google/gopacket#268]
Attempting to build https://github.com/mehrdadrad/mylg, which uses `gopacket/pcap`, but the building of `gopacket/pcap` is failing:

```
bin/gopath/src/github.com/google/gopacket/pcap/pcap.go:632: cannot use C.time_t(ci.Timestamp.Unix()) (type C.time_t) as type C.u_int32_t in assignment
bin/gopath/src/github.com/google/gopacket/pcap/pcap.go:633: cannot use C.suseconds_t(ci.Timestamp.Nanosecond() / 1000) (type C.suseconds_t) as type C.u_int32_t in assignment
```

```
$ go version
go version go1.7 openbsd/386
````

This is openbsd -current snapshot from this morning.

Here's the man page for time:
http://man.openbsd.org/OpenBSD-current/man3/time.3

**Comment by gconnell** [comment]
Hmm, I expect we'll have to add BSD to the list of defines at the top of pcap.go.

I don't have an OpenBSD system myself to check this out on, but could you pull down the https://github.com/google/gopacket/tree/openbsdtime branch and see if that fixes things for you?  If you confirm it does, I'll merge it into master.

**Comment by jungle-boogie** [comment]
Hello @gconnell,

Am I building `go build pcap/pcap.go`?

If so, that completed without errors:
```
$ go build pcap/pcap.go
$
```

**Comment by gconnell** [comment]
Should be fixed, let me know if you still have issues with the current master.
