### ISSUE TITLE
panic in dns.go

### ISSUE THREAD

**Issue by danmia** [google/gopacket#269]
I've isolated a case where a packet that is not valid DNS to port 53 causes gopacket to panic in dns.go.  I've attached a 1 packet pcap so that you may reproduce it.  I'm on the latest master.

panic: runtime error: slice bounds out of range

goroutine 51 [running]:
panic(0x79e020, 0xc420010130)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.decodeName(0xc4212f448a, 0x1d, 0x1d, 0xc, 0xc421314168, 0x1, 0xc42004f5c8, 0x6154d5, 0x42173e, 0xc16340, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:538 +0x240
github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc420063668, 0xc4212f448a, 0x1d, 0x1d, 0xc, 0x7fb1e03be0c8, 0xc421354140, 0xc421314168, 0xd, 0xc41ff675f9, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:594 +0x6f
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc4213140c0, 0xc4212f448a, 0x1d, 0x1d, 0x7fb1e03be0c8, 0xc421354140, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:328 +0x2e8
github.com/google/gopacket/layers.decodeDNS(0xc4212f448a, 0x1d, 0x1d, 0xc19ae0, 0xc421354140, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x862288, 0xc4212f448a, 0x1d, 0x1d, 0xc19ae0, 0xc421354140, 0x42173e, 0xc41ff684ab)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc4212f448a, 0x1d, 0x1d, 0xc19ae0, 0xc421354140, 0xc2c8c0, 0x422a03)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:85 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc421308980, 0xc4212f448a, 0x1d, 0x1d, 0xc19ae0, 0xc421354140, 0xc421308980, 0xc42004f8f8)

[malformed_dns_sanitized.pcap.zip](https://github.com/google/gopacket/files/646947/malformed_dns_sanitized.pcap.zip)

**Comment by gconnell** [comment]
Thanks for the great report, and the attached pcap!  Made things MUCH easier!

**Comment by danmia** [comment]
Thanks for the quick turnaround!
