### ISSUE TITLE
panic in dns.go due to malformed DNS packet

### ISSUE THREAD

**Issue by danmia** [google/gopacket#271]
I've isolated another case where given a malformed DNS packet gopacket panics decoding that layer.  I've attached a 1 packet pcap so that you can reproduce it.  

On a semi related note, is there an easy way to just disable application layer from being decoded on a PacketSource to avoid these very cases where it's not needed?  

[malformed_dns_sanitized2.pcap.zip](https://github.com/google/gopacket/files/651875/malformed_dns_sanitized2.pcap.zip)

panic: runtime error: index out of range

goroutine 12 [running]:
panic(0x79e4e0, 0xc420010130)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.decodeName(0xc4211c014a, 0x5d, 0x5d, 0x37d4, 0xc42015a3a8, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:517 +0x953
github.com/google/gopacket/layers.decodeName(0xc4211c014a, 0x5d, 0x5d, 0xc, 0xc42015a3a8, 0x1, 0xc167e0, 0xc420010308, 0x42189e, 0x3, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:568 +0x56a
github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc420049668, 0xc4211c014a, 0x5d, 0x5d, 0xc, 0x7f06a84f5558, 0xc4210ff680, 0xc42015a3a8, 0xd, 0xc41fff52e7, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:595 +0x6f
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc42015a300, 0xc4211c014a, 0x5d, 0x5d, 0x7f06a84f5558, 0xc4210ff680, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:328 +0x2e8
github.com/google/gopacket/layers.decodeDNS(0xc4211c014a, 0x5d, 0x5d, 0xc19f80, 0xc4210ff680, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x862808, 0xc4211c014a, 0x5d, 0x5d, 0xc19f80, 0xc4210ff680, 0x42189e, 0xc41ff78773)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc4211c014a, 0x5d, 0x5d, 0xc19f80, 0xc4210ff680, 0xc421193400, 0x422b63)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:85 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc4211c8620, 0xc4211c014a, 0x5d, 0x5d, 0xc19f80, 0xc4210ff680, 0xc4211c8620, 0xc4200358f8)
	<autogenerated>:14 +0x84

**Comment by gconnell** [comment]
Taking a look now.

There's a few things you can do re: application logging.

1) the default packet decoding actually just expects panics, catches them, and provides them as an error layer.
2) for DNS specifically, you can set:
  layers.RegisterUDPPortLayerType(53, gopacket.LayerTypePayload)

For all UDP layers, you can just say:  `for i := 0; i < 65536; ... { register(payload) }` as above

There should be a way to override a layer in gopacket, but apparently there isn't.  I'll add something to do that as part of the pull for the DNS fix.

**Comment by danmia** [comment]
Thanks.  I figured this was a good opportunity given the unique nature of our traffic for some deep dives and hardening the decoder while I'm in this mode as I had planned to use that on a separate project.  Being in the DDoS business, we get all manner of malformed traffic so we tend to be a good test bed for that type of thing.

**Comment by gconnell** [comment]
The reports, especially with pcaps, are definitely appreciated and do help us improve things greatly.  BTW, by default I take the actual packet data from the pcap and insert it into a test... let me know if there's any packets you'd rather not show up in our test files.

**Comment by gconnell** [comment]
Fixed by https://github.com/google/gopacket/commit/e1ff2c5f5c6309980abef5e9ae003a6a892fd11d

**Comment by danmia** [comment]
Nope. You're good.  I sanitize (IPs and mac addresses) them with tcprewrite
before I ship them over.  The payloads have been junk so nothing
identifiable there.  Probably good to just scan with your eyes and see if
anything obvious stands out but as a rule, do whatever is best for the
project.


Thanks again,
Dan
