### ISSUE TITLE
dns.go panic

### ISSUE THREAD

**Issue by danmia** [google/gopacket#274]
Should I stop submitting these?  Let me know if they get annoying.  They're not preventing me from doing anything I just figured while I was in the mode of isolating traffic I should just run through them now.

[dns-malformed-sanitized.pcap.zip](https://github.com/google/gopacket/files/655496/dns-malformed-sanitized.pcap.zip)

panic: runtime error: index out of range

goroutine 12 [running]:
panic(0x7a0c80, 0xc420012110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.decodeName(0xc4211e662a, 0x5a5, 0x5a5, 0x5a5, 0xc4201583a8, 0x2, 0x1, 0x30, 0x0, 0x0, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:517 +0xaa0
github.com/google/gopacket/layers.decodeName(0xc4211e662a, 0x5a5, 0x5a5, 0xc, 0xc4201583a8, 0x1, 0xc1a340, 0xc4200122e8, 0x4218fe, 0x3, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:571 +0x624
github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc420049668, 0xc4211e662a, 0x5a5, 0x5a5, 0xc, 0x7f61bbb51578, 0xc4210fd680, 0xc4201583a8, 0xd, 0xc41fff53e7, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:601 +0x6f
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc420158300, 0xc4211e662a, 0x5a5, 0x5a5, 0x7f61bbb51578, 0xc4210fd680, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:328 +0x2e8
github.com/google/gopacket/layers.decodeDNS(0xc4211e662a, 0x5a5, 0x5a5, 0xc1db40, 0xc4210fd680, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x8654c0, 0xc4211e662a, 0x5a5, 0x5a5, 0xc1db40, 0xc4210fd680, 0x4218fe, 0xc41ff78873)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc4211e662a, 0x5a5, 0x5a5, 0xc1db40, 0xc4210fd680, 0xc421199400, 0x422bc3)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:95 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc4211c3d10, 0xc4211e662a, 0x5a5, 0x5a5, 0xc1db40, 0xc4210fd680, 0xc4211c3d10, 0xc4200358f8)
	<autogenerated>:14 +0x84

**Comment by gconnell** [comment]
no way, these are great :)

they make me feel like I'm being productive, and they take <5 minutes to diagnose and fix each.

**Comment by lhausermann** [comment]
And as the original author of this layer (my first in gopacket) I am more than Happy to see it getting better and better
