### ISSUE TITLE
malformed dns panic dns.go

### ISSUE THREAD

**Issue by danmia** [google/gopacket#275]
Another malformed DNS packet causing a panic.  Believe it or not these are getting significantly harder to find ;)

[malformed_dns_sanitized.pcap.zip](https://github.com/google/gopacket/files/655730/malformed_dns_sanitized.pcap.zip)

panic: runtime error: index out of range

goroutine 12 [running]:
panic(0x7a0da0, 0xc420012110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.decodeName(0xc420109d8a, 0x75, 0x75, 0xc, 0xc420158228, 0x1, 0xc1a3a0, 0xc4200122e8, 0x4218fe, 0x3, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:525 +0x242
github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc420049668, 0xc420109d8a, 0x75, 0x75, 0xc, 0x7f837bf1e4b8, 0xc421101680, 0xc420158228, 0xd, 0xc41fff53f3, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:605 +0x6f
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc420158180, 0xc420109d8a, 0x75, 0x75, 0x7f837bf1e4b8, 0xc421101680, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:328 +0x2e8
github.com/google/gopacket/layers.decodeDNS(0xc420109d8a, 0x75, 0x75, 0xc1dba0, 0xc421101680, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x865620, 0xc420109d8a, 0x75, 0x75, 0xc1dba0, 0xc421101680, 0x4218fe, 0xc41ff78673)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc420109d8a, 0x75, 0x75, 0xc1dba0, 0xc421101680, 0xc42119d000, 0x422bc3)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:95 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc4211c7d00, 0xc420109d8a, 0x75, 0x75, 0xc1dba0, 0xc421101680, 0xc4211c7d00, 0xc4200358f8)
	<autogenerated>:14 +0x84

**Comment by gconnell** [comment]
They darn well better be :D

Bring it on!
