### ISSUE TITLE
panic in dns.go

### ISSUE THREAD

**Issue by danmia** [google/gopacket#276]
Consider it "brought on" ;)  
Here's another...

[malformed_dns_panic6_sanitized.pcap.zip](https://github.com/google/gopacket/files/655976/malformed_dns_panic6_sanitized.pcap.zip)

panic: runtime error: slice bounds out of range

goroutine 12 [running]:
panic(0x7a0660, 0xc420012140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.decodeName(0xc42117758a, 0x5d, 0x5d, 0xc, 0xc42015c228, 0x1, 0xc194e0, 0xc420012308, 0x4218fe, 0x3, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:563 +0x720
github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc42004b668, 0xc42117758a, 0x5d, 0x5d, 0xc, 0x7f36ecb3c588, 0xc421103680, 0xc42015c228, 0xd, 0xc41fff51f3, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:598 +0x6f
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc42015c180, 0xc42117758a, 0x5d, 0x5d, 0x7f36ecb3c588, 0xc421103680, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:328 +0x2e8
github.com/google/gopacket/layers.decodeDNS(0xc42117758a, 0x5d, 0x5d, 0xc1cc80, 0xc421103680, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x864bc0, 0xc42117758a, 0x5d, 0x5d, 0xc1cc80, 0xc421103680, 0x4218fe, 0xc41ff78573)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc42117758a, 0x5d, 0x5d, 0xc1cc80, 0xc421103680, 0xc42119d400, 0x422bc3)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:95 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc4211c7fc0, 0xc42117758a, 0x5d, 0x5d, 0xc1cc80, 0xc421103680, 0xc4211c7fc0, 0xc4200378f8)
	<autogenerated>:14 +0x84

**Comment by gconnell** [comment]
I'm having to get creative with my packet slice names:  https://github.com/google/gopacket/blob/master/layers/dns_test.go#L730

**Comment by danmia** [comment]
lol!!!  I'm doing the same thing with pcap file names locally.  I'm in Miami so you'll have overnight to think of some more.  I'll be laughing about that last one for quite awhile.

**Comment by vtolstov** [comment]
May be use go-fuzz can help with such errors?

**Comment by gconnell** [comment]
It's definitely possible, and I'll certainly accept pull requests for it.

That said, I initially wrote gopacket with the expectation that layer decoding would panic... hence the Packet decoding by default catching those.  It was just easier, when I was churning out 10s of different layer types, to write fewer if statements.  And it meant that others contributing layers could do so more easily, too.
