### ISSUE TITLE
panics (dns.go) ... They're what's for dinner.

### ISSUE THREAD

**Issue by danmia** [google/gopacket#277]
Found another interesting one.

[dnsgo.panic7.single_sanitized.pcap.zip](https://github.com/google/gopacket/files/658097/dnsgo.panic7.single_sanitized.pcap.zip)

panic: runtime error: slice bounds out of range

goroutine 12 [running]:
panic(0x7a1300, 0xc420012140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.(*DNSResourceRecord).decode(0xc4211e8560, 0xc420075d6a, 0x200, 0x200, 0x1ee, 0x7f63cf471568, 0xc4210ff680, 0xc42015a228, 0x1ee, 0x0, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:687 +0x334
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc42015a180, 0xc420075d6a, 0x200, 0x200, 0x7f63cf471568, 0xc4210ff680, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:355 +0x74f
github.com/google/gopacket/layers.decodeDNS(0xc420075d6a, 0x200, 0x200, 0xc1e260, 0xc4210ff680, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x865bc0, 0xc420075d6a, 0x200, 0x200, 0xc1e260, 0xc4210ff680, 0x4218fe, 0xc41ff78773)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc420075d6a, 0x200, 0x200, 0xc1e260, 0xc4210ff680, 0xc421199400, 0x422bc3)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:95 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc4211cc640, 0xc420075d6a, 0x200, 0x200, 0xc1e260, 0xc4210ff680, 0xc4211cc640, 0xc4200378f8)
	<autogenerated>:14 +0x84

**Comment by gconnell** [comment]
Back from Xmas break, time to fix DNS bugs :D
