### ISSUE TITLE
Missing file pcap/pcap.h

### ISSUE THREAD

**Issue by jamiesellick93** [google/gopacket#280]
C:\Install\GoReplay\src\github.com\buger\gor\vendor\github.com\google\gopacket\pcap\pcap.go:21:18: fatal error: pcap.h: No such file or directory

Compilation fails on Windows, compiling as a submodule of GoReplay

**Comment by gconnell** [comment]
libpcap for Windows needs to be installed/findable to use gopacket/pcap on Windows machines.

**Comment by sudo-suhas** [comment]
Got this error on ubuntu 18.04:
```
go get github.com/ga0/netgraph
# github.com/google/gopacket/pcap
installs/go-tools/src/github.com/google/gopacket/pcap/pcap.go:22:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.

```

Should I create a new issue?

**Comment by gconnell** [comment]
For Ubuntu, you should be able to:

`sudo apt-get install libpcap-dev`

**Comment by sudo-suhas** [comment]
Thanks @gconnell, that worked.

**Comment by clholzin** [comment]
I needed to install these and it worked
libpcap-dev libpcap0.8 libpcap0.8-dev

**Comment by RobinUS2** [comment]
Any thoughts for OSX? Trying to cross compile for a windows machine.

**Comment by KodyKendall** [comment]
@clholzin thank you. Had to install libpcap0.8-dev, which wasn't included in libpcap-dev.

**Comment by Mariosiburian** [comment]
root@localhost:~/Pyrit# python setup.py build
running build
running build_py
running build_ext
building 'cpyrit._cpyrit_cpu' extension
aarch64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oBClzS/python2.7-2.7.18~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-aarch64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.1"
cpyrit/_cpyrit_cpu.c:40:10: fatal error: pcap.h: No such file or directory
   40 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.


Please how to solve this problem..

**Comment by gconnell** [comment]
Try:  apt-get install libpcap-dev

**Comment by Mariosiburian** [comment]
I installed it, but there are still no changes.

**Comment by Mariosiburian** [comment]
1. wlan0       null  ??????              non-mac80211 device? (report this!)

 [+] enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find any interfaces in Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/root/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/root/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 190, in start
 [!]        raise Exception('Cannot find any interfaces in Mode:Monitor')
 [!]  Exception: Cannot find any interfaces in Mode:Monitor

 [!] Exiting


HELP MEEE :(

**Comment by Shaif111** [comment]
Thanks you so much gconnell

**Comment by ArisAachen** [comment]
I have still met up this issue.  
That is so strange since I have <pcap.h> installed.  
Anyone for help, please 

``` shell
❯ ls -al /usr/include/pcap.h
-rw-r--r-- 1 root root 2226 2022年 2月 4日 /usr/include/pcap.h

❯ uname -a
Linux aris-PC 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux
```
