### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by mqliang** [google/gopacket#281]
It would be wonderful to provide a sample code for using the gopacket TCP assembler and TCP stream reader to decode HTTPS request/response, assuming that user could provide crt and key files

**Comment by c1982** [comment]
Yes. agree.
I do not know where to start about this.

**Comment by lhausermann** [comment]
You should start with having a look to examples/reassemblydump and maybe add TLS support on it using the Golang native SSL stack.

**Comment by lhausermann** [comment]
Any progress guys?
