### ISSUE TITLE
Random nil pointer errors pcap

### ISSUE THREAD

**Issue by chughtapan** [google/gopacket#284]
I am using gopacket with pcap to read live packets over an interface. I randomly keep getting nil pointer errors

Stack trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20]

goroutine 1 [running]:
main.main
	/home/tapan/go/src/test.go:54

goroutine 5 [runnable]:
github_com_google_gopacket_pcap.ReadPacketData.pN38_github_com_google_gopacket_pcap.Handle
	/home/tapan/go/src/github.com/google/gopacket/pcap/pcap.go:295
github_com_google_gopacket.NextPacket.pN39_github_com_google_gopacket.PacketSource
	/home/tapan/go/src/github.com/google/gopacket/packet.go:787
github_com_google_gopacket.packetsToChannel.pN39_github_com_google_gopacket.PacketSource
	/home/tapan/go/src/github.com/google/gopacket/packet.go:804
created by github_com_google_gopacket.Packets.pN39_github_com_google_gopacket.PacketSource
	/home/tapan/go/src/github.com/google/gopacket/packet.go:827
```
Code:

    handle, err = pcap.OpenLive("eth0", 1024, true, 1 * time.Second)
    if err != nil {fmt.Println(err) }
    defer handle.Close()
    packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
    data:= make(map[gopacket.Flow]int) 
    for packet := range packetSource.Packets() {
        fmt.Println(packet)
    }

I tried to look through the code but could not find anything.

**Comment by gconnell** [comment]
It looks like you're checking the error, but then still using the handle?  If `OpenLive` returns a non-nil error, it'll return a nil handle, so calling `handle.Anything()` will result in a nil-pointer as you've described.

Try:

```go
handle, err := pcap.OpenLive(...)
if err != nil {
  log.Fatal(err)  // Stops execution
}
... do more stuff ...
```

**Comment by chughtapan** [comment]
Sorry, I realized I did't make it clear enough. I see this while the packets are being captured. The packet capture suddenly stalls and then dies with the above error, though traffic is still going through the network.
PS: Thanks for pointing out that bug anyway

**Comment by chughtapan** [comment]
Just realised the error was occuring due to ARP packets coming in between which do not have a network layer at all. 
Thanks
