### ISSUE TITLE
Why IGMP does not implement SerializeTo method like other layers

### ISSUE THREAD

**Issue by inoyatov** [google/gopacket#285]
I was surprised why IGMP layer does not implement SerializeTo method like other layers. Is there some special reason to do so? Or should it be fixed?

**Comment by gconnell** [comment]
Serialization was added to the library after a number of layers were already implemented, IGMP included.  There hasn't yet been a comprehensive effort to implement serialization in every layer... instead we tend to wait for folks to need it.  If you'd like to implement IGMP serialization, we'd love to have it!  :D

**Comment by lhausermann** [comment]
Closing this after a 3 month of idle...
