### ISSUE TITLE
LinkType enum is uint8 but tcpdump defines linktypes > 255

### ISSUE THREAD

**Issue by PaulMcMillan** [google/gopacket#289]
The LinkType type is a uint8:
https://github.com/google/gopacket/blob/master/layers/enums.go#L93
However, the canonical list of linktype numbers currently has a max of 266. 
http://www.tcpdump.org/linktypes.html

Additionally, looking at the pcap documentation, it looks like that is returned as an int
http://www.tcpdump.org/manpages/pcap_datalink.3pcap.txt
and when we use that function, we also use an int
https://github.com/google/gopacket/blob/master/pcap/pcap.go#L651
Edit: oh, I see how that works. The `layers.LinkType()` is casting the int to uint8.

I'm also not sure how to solve this in a fully backwards compatible way, but I figured I should bring it up since I noticed it...

**Comment by lhausermann** [comment]
Hi. Thanks for reporting it. Uint8 are used to optimize the lookup per the number of layer we actually support. I think that would be updated once we'll see the need for it.
