### ISSUE TITLE
UDP Packet malformed with ComputeChecksums = true

### ISSUE THREAD

**Issue by ebiken** [google/gopacket#290]
I found packet will be malformed when sending UDP packet with SerializeOptions.ComputeChecksums = true.

I wrote a short program to test this and uploaded here:
https://github.com/ebiken/sandbox/blob/master/gopacket-udp-malform.go

What I did was define ethernet/ipv4/udp layer, build packet using SerializeLayers() and send it to lo (loopback).
I did two trials:
1. Disabling ComputeChecksums by commenting out line 33
2. Enable ComputeChecksums by commenting in line 33. (as shown below)

```
 33     options.ComputeChecksums = true

 75     buffer = gopacket.NewSerializeBuffer()
 76     gopacket.SerializeLayers(buffer, options,
 77         ethernetLayer,
 78         ipv4Layer,
 79         udpLayer,
 80         gopacket.Payload(rawBytes),
 81     )
 82     err = handle.WritePacketData( buffer.Bytes() )
```

I checked packets by capturing it on lo using tshark.
You can find the first packet (ComputeChecksums = false) is correct and 2nd one (ComputeChecksums = true) is malformed.

```
root@md:~# tshark -i lo -xV -O gtp

Frame 1: 60 bytes on wire (480 bits), 60 bytes captured (480 bits) on interface 0
Ethernet II, Src: 02:00:00:00:00:01 (02:00:00:00:00:01), Dst: 06:00:00:00:00:01 (06:00:00:00:00:01)
Internet Protocol Version 4, Src: 10.0.0.2, Dst: 127.0.0.1
User Datagram Protocol, Src Port: 9999 (9999), Dst Port: 2152 (2152)
Data (16 bytes)

0000  06 00 00 00 00 01 02 00 00 00 00 01 08 00 45 00   ..............E.
0010  00 2c 00 00 00 00 ff 11 00 00 0a 00 00 02 7f 00   .,..............
0020  00 01 27 0f 08 68 00 18 00 00 00 00 00 00 00 00   ..'..h..........
0030  00 00 00 00 00 00 00 00 00 00 00 00               ............

Frame 2: 24 bytes on wire (192 bits), 24 bytes captured (192 bits) on interface 0
Ethernet II, Src: 00:00:00_00:00:00 (00:00:00:00:00:00), Dst: 27:0f:08:68:00:18 (27:0f:08:68:00:18)
TDMoP protocol
[Malformed Packet: TDMoP]

0000  27 0f 08 68 00 18 00 00 00 00 00 00 00 00 00 00   '..h............
0010  00 00 00 00 00 00 00 00                           ........
```

**Comment by ebiken** [comment]
When I revied SerializeLayers() in "writer.go", it was serializing from upper layer. ex: udp->ipv4->ethernet.
So IPv4 does not exist in the buffer when `func (u *UDP) SerializeTo()` is called.
However, `func (c *tcpipchecksum) computeChecksum()` requires network layer (IPv4) when calculating checksum for UDP.

```
77        return 0, errors.New("TCP/IP layer 4 checksum cannot be computed without network layer... call SetNetworkLayerForChecksum to set which layer to use")
```

Could this be part of the cause of malformed packet?

**Comment by gconnell** [comment]
I believe if you check the error returned from `SerializeLayers()`, you should see the error you've mentioned in line 77.  In order to fix this, call this at line 73:

```go
udpLayer.SetNetworkLayerForChecksum(ipv4Layer)
```

If this doesn't solve the issue, feel free to reopen.

**Comment by ebiken** [comment]
Appreciate your advice.

Noting it actually worked after adding a line of code above for future reference.

ebiroot@md:~$ sudo tshark -i lo -Vx -o udp.check_checksum:TRUE -O udp
Frame 1: 60 bytes on wire (480 bits), 60 bytes captured (480 bits) on interface 0
Ethernet II, Src: 02:00:00:00:00:01 (02:00:00:00:00:01), Dst: 06:00:00:00:00:01 (06:00:00:00:00:01)
Internet Protocol Version 4, Src: 10.0.0.2, Dst: 127.0.0.1
User Datagram Protocol, Src Port: 9999 (9999), Dst Port: 2152 (2152)
    Source Port: 9999
    Destination Port: 2152
    Length: 24
    Checksum: 0x4744 [correct]
        [Calculated Checksum: 0x4744]
        [Good Checksum: True]
        [Bad Checksum: False]
    [Stream index: 0]
Data (16 bytes)

**Comment by gconnell** [comment]
Thanks for comfirming :)

If you have any additional questions or concerns, please don't hesitate to post.
