### ISSUE TITLE
How to get MTU and MAC address by gopacket apis?

### ISSUE THREAD

**Issue by smcduck** [google/gopacket#291]
pcap.FindAllDevs() returns many information of NICs, but no MTU and MAC address.

Golang net.InterfaceByName() could get MTU and MAC, but it can't get NIC description under windows, the description is useful to judge NIC is physical or virtual. So, I am trying to get MTU and MAC address by gopacket apis.

**Comment by lhausermann** [comment]
These information are most of time per platform so I recommend to use native API.
