### ISSUE TITLE
Support Nanosecond timestamp in pcap files 

### ISSUE THREAD

**Issue by markassad** [google/gopacket#298]
There's currently no support for getting nanosecond timestamps out of read pcap files using the libpcap library. There is currently support for this in the pcapgo module, but using the C pcap library will allow me to use the BPF filter. 

I'm happy to do the work to make the change if you are happy to accept it, but wanted feedback on the approach before I started. 

I was going to use the pcap_fopen_offline_with_tstamp_precision method to open the pcap files, if it existed. If it did not, then I will create a stub implementation, similar to how pcap_set_immediate_mode is stubbed out. If the sub method is used, then read time stamps will be multiplied by 1000. 

For live captures, I wanted to add a call to "pcap_set_tstamp_precision" to set the precision to nanoseconds, and again, if it fails, do the multiply. 

I don't see this having any external effects on the library because all time stamps are exposed as a Timestamp which is a nanosecond format. 

Thanks for your comments.

**Comment by lhausermann** [comment]
Hi @markassad I think this would be a good way to add nanosec precision. 
I am wondering how this will be portable accross all the different OS we support including Windows.
Do you have any idea ?

**Comment by markassad** [comment]
Hi @lhausermann I was leaving that up to the libpcap library. libpcap has added a bunch of functions that optionally turn on the nanosecond precision. If those functions are supported, then the gopacket Timestamp field will be filled with a higher precision timestamp. For other OSs that do not support this feature, the Timestamp field will be left as Microsecond precision.

It is probably worth adding a function to that allows the user of the library to query the current precision of the packet source. 

The hard part is being able to optionally supporting the pcap_*_tstamp_precision functions. For live functions, this is straight forward. pcap_set_tstamp_precision returns an error code that indicates if it failed, and so it can be stubbed out. For pcap_fopen_offline_with_tstamp_precision it assumes that the it will always be able to set the higher precision.  This means that it is not possible to simple create a stub function that the Go code can call that passes through to the  pcap_fopen_offline and still tell the Go code that the file was only opened in Microsecond precision.  I may need to add a #define in the cgo stub that can be used to tell the Go code if nanoseconds are supported.

**Comment by lhausermann** [comment]
OK, if you'd like to try, I'll review it

**Comment by lhausermann** [comment]
Hi. Any news on this one?
