### ISSUE TITLE
timestamp in decoded packet

### ISSUE THREAD

**Issue by arpitjain305** [google/gopacket#315]
On decoding the various layers in the packet, I couldn't find the timestamp when that packet was received on the network. I checked layers.Ethernet, layers.IPv4, layers.TCP, but couldn't find the timestamp field

**Comment by gconnell** [comment]
None of those layers actually contain that information, and given that various machines have different ideas of what time it is.

You can get this (local) time information from gopacket by looking at a packet's `CaptureInfo`. If you have a gopacket.Packet p, run `p.Metadata().Timestamp`.  If you're using a `PacketDataSource` directly, just look at the `captureInfo.Timestamp` from the `CaptureInfo` returned by the `ReadPacketData` call.

**Comment by arpitjain305** [comment]
Thanks. 
Just one more question. On calling handle.close() (i.e, closing pcap handle), does it also close the underlying channel on which packets are written (I'm using  gopacket.NewPacketSource)

**Comment by gconnell** [comment]
Short answer:  Yes, it should.

Once a pcap.Handle is closed, ReadPacketData should return io.EOF, which PacketSource's channel writer (https://github.com/google/gopacket/blob/master/packet.go#L813) should use to close the channel.
