### ISSUE TITLE
pfring using crazy amount of CPU

### ISSUE THREAD

**Issue by shang-wang** [google/gopacket#320]
Hi all:

I'm playing with different options in gopacket so that I could capture packets in the least resource consuming fashion. I was testing `pcap`, `afpacket` then found `pfring`, read online and learnt that `pfring` is suppose to be "high performance", so I plugged it into my simple program and try it out. On a server that has rx/tx of 100MB/sec traffic, `pfring` program consumes 600% CPU(!!),
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   560 root      20   0 1594024 324860 264524 S 629.4  0.3   0:38.57 simple_pfring
```

whereas `pcap` and `afpacket` uses around 40%. It roughly looks like this:
```
package main

import (
        "fmt"
        "github.com/google/gopacket"
        "github.com/google/gopacket/layers"
        "github.com/google/gopacket/pfring"
)

func main() {
        if ring, err := pfring.NewRing("eth0", 65536, pfring.FlagPromisc); err != nil {
                panic(err)
        } else if err := ring.Enable(); err != nil { // Must do this!, or you get no packets!
                panic(err)
        } else {
                packetSource := gopacket.NewPacketSource(ring, layers.LinkTypeEthernet)
                counter := 0
                size := 0
                for packet := range packetSource.Packets() {
                        counter += 1
                        size += len(packet.Data())
                        if counter%1000 == 0 {
                                fmt.Printf("Number of packets:%d, total size: %d\n", counter, size)
                        }
                }
        }
}
```

What am I missing here?

By the way, my goal is to make my program acting as a collect agent and uses as little CPU as possible, ideally between 10% ~ 20%. I don't need to analyse the payload, just need to get basic info like src/dest IP/port and packet size. I do notice the `NewDecodingLayerParser` and `ZeroCopyReadPacketData` thanks to [this](https://github.com/google/gopacket/blob/master/examples/statsassembly/main.go) example, but that's about it. Any suggestions? Maybe even a different library? Thanks!!

**Comment by gconnell** [comment]
hmm, that doesn't sound good at all :P 

That sounds a good bit like there's some sort of busy loop happening under the covers.  Unfortunately, ATM I don't have any computers with PF_RING installed at my disposal, so I may have to vicariously debug this through you, if you're willing.

Could you potentially modify your program with:

```go
import (
  "runtime/pprof"
  "os"
)

func main() {
  f, _ := os.Create("/tmp/cpuprofile")
  pprof.StartCPUProfile(f)
  defer pprof.StopCPUProfile()
  ... do pfring startup ...
  for ... {
    ...
    if counter > 1000000 { return }  // so program eventually stops and we get a valid CPU profile
  }
}
```

Once you've run that, you should be able to say:

```sh
$ go tool pprof <binary> /tmp/cpuprofile
> top50
> web
```

to visualize exactly where the CPU cycles are being used.

**Comment by shang-wang** [comment]
Hey @gconnell:

Thanks for your speedy reply. I was kind of in a rush on the first try, I did some changes to the program, like this:
```
package main

import (
        "fmt"
        "github.com/google/gopacket/pfring"
)

func main() {
        if ring, err := pfring.NewRing("eth0", 1600, pfring.FlagPromisc); err != nil {
                panic(err)
        } else if err := ring.Enable(); err != nil { // Must do this!, or you get no packets!
                panic(err)
        } else {
                counter := 0
                size := 0
                for {
                        _, ci, err := ring.ReadPacketData()
                        if err != nil {
                                panic(err)
                        }
                        counter += 1
                        size += ci.Length
                        if counter%1000 == 0 {
                                fmt.Printf("Number of packets:%d, total size: %d\n", counter, size)
                        }
                }
        }
}
```
Now it looks much better:

**Comment by gconnell** [comment]
Hmm, if that's the case, then it appears the majority of the CPU might actually be in the packet decoding (pulling out packet layers and the like).  Given that, I'd expect use of the DecodingLayerParser would be what you're looking for:  it'll decode packets, but won't do all of the malloc magic behind the scenes to create new layer objects for each packet layer, etc.

To be sure it's the decoding that's causing issues, maybe change this line of your original program and rerun:

```go
< packetSource := gopacket.NewPacketSource(ring, layers.LinkTypeEthernet)
> packetSource := gopacket.NewPacketSource(ring, layers.LinkTypeEthernet, gopacket.Lazy)
```

That will turn on lazy decoding, which only decodes layers when they're seen... you'll still probably have more CPU usage than your second program, because the actual Packet object is still being created, but all the decoding and Layer object creation is skipped.

Going to close this for now, but feel free to reopen if your profiling finds anything really interesting going on.
