### ISSUE TITLE
Does pfring support device "lo"?

### ISSUE THREAD

**Issue by shang-wang** [google/gopacket#321]
Hi all:

I was trying to use `pfring` module to capture traffic on interface `lo`, but I got
```
panic: pfring NewRing error: no such device
```
I'm initializing the ring with simply:
```
ring, err := pfring.NewRing("lo", 1600, pfring.FlagPromisc)
```
But when I do that using `pcap` or `afpacket`, they work:
```
handle, err := afpacket.NewTPacket(
                afpacket.OptInterface("lo"),
                afpacket.OptFrameSize(frame_size),
                afpacket.OptBlockSize(block_size),
                afpacket.OptNumBlocks(num_blocks))
```
or 
```
handle, err := pcap.OpenLive("lo", 1600, true, 2*time.Second)
```

What am I missing? Or it's not supported? Thanks!

PS: I'm also wondering if one single ring/handle would bind to "any" interface, which captures packet from all interfaces? Then I don't have to explicitly define one ring per interface.

**Comment by gconnell** [comment]
Hmm, weird.  Unfortunately, I currently don't have a machine with PF_RING installed, but I believe it should come with a `pfcount` test binary (written in C) that just counts packets on the wire, and which may accept an interface name as a command-line arg.  I'd see if you can pass `lo` in as the interface to `pfcount`, and if you get the same error it's almost definitely a PF_RING support issue for that interface type.  If that works, we may need to dig deeper to figure out what's going on.

**Comment by shang-wang** [comment]
Hi @gconnell 
Thanks for pointing that out, totally forgot about that. I had a chance to test it today and here's the result:

```
vagrant@ubuntu-1404:~/PF_RING/userland/examples [13:15:10][dev] $ sudo ./pfcount -i lo
pfring_open error [No such device] (pf_ring not loaded or interface lo is down ?)
vagrant@ubuntu-1404:~/PF_RING/userland/examples [13:15:31][dev] $ sudo ./pfcount -i eth0
Using PF_RING v.6.7.0
Capturing from eth0 [mac: 08:00:27:AD:41:5D][if_index: 2][speed: 1000Mb/s]
# Device RX channels: 1
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/2852-eth0.16
=========================
Absolute Stats: [1 pkts total][0 pkts dropped][0.0% dropped]
[1 pkts rcvd][84 bytes rcvd]
=========================
......
```
It clearly shows that `lo` is not recognized but `eth0` is. Sounds like it worths to open an issue upstream but thanks again for your help, feel free to close/leave the ticket.

**Comment by shang-wang** [comment]
Hey @gconnell 
Didn't mean to reopen the ticket but just want to leave a comment about this: https://github.com/ntop/PF_RING/issues/221. Thanks.
