### ISSUE TITLE
packetsource channel close on pcap handle close

### ISSUE THREAD

**Issue by arpitjain305** [google/gopacket#326]
I created a pcap handle (via pcap.OpenLive) and used it to create a packetsource (via gopacket.NewPacketSource(...)). The packetsource channel (i.e, packetSource.Packets()) is returning packets as desired, but I wanted to know whether that channel gets closed (or rather, does the libpcap stop reading anymore packets) if I close the pcap handle?

**Comment by gconnell** [comment]
If the `PacketDataSource` correctly returns `io.EOF` when it reaches its end, the channel will correctly close.  See https://github.com/google/gopacket/blob/master/packet.go#L813

```go
// packetsToChannel reads in all packets from the packet source and sends them
// to the given channel.  When it receives an error, it ignores it.  When it
// receives an io.EOF, it closes the channel.
func (p *PacketSource) packetsToChannel() {
	defer close(p.c)
	for {
		packet, err := p.NextPacket()
		if err == io.EOF {
			return
		} else if err == nil {
			p.c <- packet
		}
	}
}
```

Note that the channel close is deferred, and that on EOF we return from the function (thus running the defer and closing the channel).  I haven't specifically looked to see if pcap's live data source returns `io.EOF` correctly on close, but if it doesn't, please open up an issue :)

**Comment by arpitjain305** [comment]
Hi, actually I was wondering what would be the behaviour if I just closed the pcap handle (by calling handle.Close()), without an EOF coming. Basically, I just want to capture packets for a short duration only, and keep repeating this after a fixed interval
