### ISSUE TITLE
could not determine kind of name for C.sizeof_struct_tpacket3_hdr

### ISSUE THREAD

**Issue by cdevoe57** [google/gopacket#328]
I'm attempting to install this and run it on a system Running Oracle Linux (red hat)
Linux server.x.y 4.1.12-61.1.25.el6uek.x86_64 #2 SMP Wed Jan 11 19:13:03 PST 2017 x86_64 x86_64 x86_64 GNU/Linux via the JustinAzoff/can-i-use-afpacket-fanout

I get the following error.

go get github.com/JustinAzoff/can-i-use-afpacket-fanout

github.com/google/gopacket/afpacket

could not determine kind of name for C.sizeof_struct_tpacket3_hdr

**Comment by notti** [comment]
This error message means that `struct tpacket3_hdr` is not defined. This would be caused by outdated linux headers.
