### ISSUE TITLE
dhcpv6

### ISSUE THREAD

**Issue by tutley** [google/gopacket#334]
Add support for handling dhcpv6 packets

https://en.wikipedia.org/wiki/DHCPv6

**Comment by evilsocket** [comment]
also interested in this, meanwhile I'll use https://godoc.org/github.com/mdlayher/dhcp6

**Comment by gconnell** [comment]
An excellent request, and a good opportunity for anyone who wants to dip their toe into contributing a packet parser :)

**Comment by evilsocket** [comment]
I might, in a while. Using gopacket for http://github.com/evilsocket/bettercap-ng

**Comment by notti** [comment]
This has been resolved by #482
