### ISSUE TITLE
pcap.OpenOffline() doesn't check if file exists

### ISSUE THREAD

**Issue by skamoen** [google/gopacket#340]
When opening a pcap with `pcap.OpenOffline(file)`, it doesn't check if the file exists. I would expect a non-nil error when this happens. Instead, all seems well until you call a method on the returned `handle` and you get nil-pointer exceptions.

Would something like this be appropriate in this case?
```
if _, err := os.Stat("/path/to/whatever"); os.IsNotExist(err) {
  // return error
}
```
(taken from https://stackoverflow.com/questions/12518876/how-to-check-if-a-file-exists-in-go)

**Comment by gconnell** [comment]
Can you let me know what platform you're running on?  I'm unable to replicate this behavior.  I've added a test to pcap_test.go, and it appears to show that we're already checking for file existence:

```sh
gconnell@gconnell:~/go/src/github.com/google/gopacket/pcap$ go test --test.v --test.run=exist
=== RUN   TestPcapNonexistentFile
--- PASS: TestPcapNonexistentFile (0.00s)
        pcap_test.go:24: Error returned for nonexistent file: /path/to/nonexistent/file: No such file or directory
PASS
ok      github.com/google/gopacket/pcap 0.115s
```

Test added in 728d569fa6e42a8fe1c6ef4bd9ca7b26ff1ba3c2

**Comment by skamoen** [comment]
I'm running [this](https://github.com/skamoen/pcapfiltermerge/blob/master/main.go) code on Linux (Arch, x64). I provide a `-path` flag to a folder containing some pcaps. The code is still a bit hacky, so you can test the behaviour by omitting a trailing slash. When the path is wrong, I get the following output:

```
$ ./main -path /home/.../Downloads/pcap
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5af132]

goroutine 1 [running]:
github.com/google/gopacket/pcap.(*Handle).LinkType(0x0, 0x12)
	/src/github.com/google/gopacket/pcap/pcap.go:695 +0x22
main.filterPcap(0xc4211032c0, 0x2d, 0x1a, 0xc421102c1b, 0x13)
	/src/github.com/skamoen/pcapfiltermerge/main.go:69 +0xe0
main.main()
	/src/github.com/skamoen/pcapfiltermerge/main.go:50 +0x448
```

Based on your test I feel like I'm missing something trivial but I can't find it.

**Comment by gconnell** [comment]
That was a head-scratcher!  Problem found, though.

Old code:

```go
func filterPcap(file string) []gopacket.Packet {
	//TODO: Check if file exists
	handle, err := pcap.OpenOffline(file)
	if err != nil {
		fmt.Errorf("couldn't open pcap", err)
	}
```

New (fixed) code:
```go
func filterPcap(file string) []gopacket.Packet {
	//TODO: Check if file exists
	handle, err := pcap.OpenOffline(file)
	if err != nil {
		log.Fatalf("couldn't open pcap: %v", err)
	}
```

In short, inside your error checking, you WERE getting back a non-nil error, but you were just calling `fmt.Errorf`, which creates and returns an error object, but doesn't stop the flow of execution (or print anything).  You probably wanted `log.Printf` and a `return` or something like that.  Using `log.Fatalf` (which crashes the program) makes this much more obvious, and crashes the program before you use a (nil) handle later on in the `filterPcap` function.

**Comment by skamoen** [comment]
Thank you so much for taking the time to figure this out! I only started working with Go a couple of weeks ago, so I haven't fully figured out the error handling part yet. Thanks again, learned something today 😄

**Comment by gconnell** [comment]
Welcome to Go!  Feel free to open additional issues any time you find something wonky ;)
