### ISSUE TITLE
Cross compile to Windows from Linux gives error in pcap_windows.go for arpscan

### ISSUE THREAD

**Issue by rcordeau** [google/gopacket#354]
Running:
GOOS=windows GOARCH=amd64 go build github.com/google/gopacket/examples/arpscan 

Result:
src/github.com/google/gopacket/pcap/pcap_windows.go:14:10: undefined: Handle

What is the best resolution for this?

**Comment by jrudio** [comment]
I don't have a resolution, but would like to mention that I am I'm trying to run the examples as well and am getting the same error.

I'm running windows/amd64

I'm not sure why it can't see `Handle` in pcap.go

**Comment by gconnell** [comment]
Unfortunately, I don't have a windows machine, so debugging/fixing this is going to be difficult on my end... if anyone with a Windows box is able to step up and look into things, it'd be greatly appreciated.

**Comment by jrudio** [comment]
@gconnell Welp, I managed to get the examples running by following https://stackoverflow.com/questions/38047858/compile-gopacket-on-windows-64bit 

Which I found via issue #159. Honestly, I should have read `pcap/doc.go`.

**Comment by rcordeau** [comment]
Well crapola. I swear I searched and searched for an answer before I filed a bug. Thanks for tracking it down.
