### ISSUE TITLE
bsdbpf captures broken frames because of wrong BPF_ALIGNMENT

### ISSUE THREAD

**Issue by ccsexyz** [google/gopacket#355]
In my machine, the BPF_ALIGNMENT in /usr/include/bpf.h is 4 while the wordSize is 8 in [bsd_bpf_sniffer.go](https://github.com/google/gopacket/blob/93b782132903d1846aab74cb1f62e6138564949f/bsdbpf/bsd_bpf_sniffer.go#L22).
Wrong wordSize resulted in a large number of broken frames.Everything goes ok after I manually modify the wordSize to 4.
```
$ uname -a
Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ go version
go version go1.9 darwin/amd64
```
<img width="279" alt="2017-09-25 8 39 54" src="https://user-images.githubusercontent.com/13003124/30808809-19cc924c-a232-11e7-83ec-da6f0412a70e.png">

Could you fix this?

**Comment by hdm** [comment]
This is stil a problem, causing drops on non-macOS BSD. My workaround:

```
