### ISSUE TITLE
Working example for WritePacket

### ISSUE THREAD

**Issue by andreyferriyan** [google/gopacket#358]
Hi, I'm searching for working example for WritePacket from pcapgo. This is an example from godoc.

`w.WritePacket(gopacket.CaptureInfo{...}, data1)`

I'm sorry but I can't find it in example or documentation from godoc. How do we put all layer we defined into **data1** ?.

Thank you.

**Comment by florianl** [comment]
`data1` is just a `[]byte`. So just create a `[]byte` and insert the bytes of all layers.

**Comment by andreyferriyan** [comment]
ah thank you, I'll try it

**Comment by florianl** [comment]
Maybe this helps:

`package main

import (
	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
	"github.com/google/gopacket/pcapgo"
	"net"
	"os"
	"time"
)

func main() {
	layer1 := &layers.Ethernet{
		SrcMAC: net.HardwareAddr{0x01, 0x02, 0x03, 0x0d, 0x0e, 0x0f},
		DstMAC: net.HardwareAddr{0xff, 0xff, 0xff, 0xff, 0xff, 0xff},
	}
	layer2 := &layers.IPv6{
		SrcIP:   net.IP{0xFE, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02},
		DstIP:   net.IP{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01},
		Version: 6,
	}
	buf := gopacket.NewSerializeBuffer()

	opts := gopacket.SerializeOptions{
		FixLengths:       true,
		ComputeChecksums: true,
	}
	gopacket.SerializeLayers(buf, opts, layer1, layer2)
	packet := buf.Bytes()

	f, _ := os.Create("/tmp/file.pcap")
	w := pcapgo.NewWriter(f)
	w.WriteFileHeader(65536, layers.LinkTypeEthernet)
	w.WritePacket(gopacket.CaptureInfo{Timestamp: time.Now(), Length: len(packet), CaptureLength: len(packet), InterfaceIndex: 0}, packet)
	f.Close()
}
`

**Comment by andreyferriyan** [comment]
Hi, sorry for late response. I think this is good example.
