### ISSUE TITLE
Ethernet layer padding packets it shouldn't be? 

### ISSUE THREAD

**Issue by arup42** [google/gopacket#361]
I noticed that arp packets generated by the arpscan demo show up with a bunch of extra padding in tcpdump as compared to those generated by the linux kernel: 

From arpscan: 

18:19:06.287898 ARP, Request who-has 10.0.0.135 tell 10.0.0.217, length 46
        0x0000:  0001 0800 0604 0001 00e0 4c04 00c1 0a00
        0x0010:  00d9 0000 0000 0000 0a00 0087 0000 0000
        0x0020:  0000 0000 0000 0000 0000 0000 0000

From the linux kernel: 

18:28:11.165183 ARP, Request who-has 10.0.0.135 tell 10.0.0.217, length 28
        0x0000:  0001 0800 0604 0001 00e0 4c04 00c1 0a00
        0x0010:  00d9 0000 0000 0000 0a00 0087

This difference is caused by the code near the end of SerializeTo() in gopacket/layers/ethernet.go, which pads short packets out to 60 bytes, presumably because ethernet frames are supposed to be at least 64 bytes in length. Disabling that code produces identical packets, and both versions seem to work.

I'm not sure whether or not packets injected to pcap_sendpacket are supposed to have had this padding already applied. Who is wrong here? gopacket or the linux kernel? Is this difference harmless?

**Comment by florianl** [comment]
As you mentioned, there is a minimum (and also maximum) size for ethernet frames. And both implementations are correct. If the packet does not fit these requirements, the network interface will modify it. In case of gopacket, this padding is done in `gopacket/layers/ethernet.go`. For the Linux kernel the padding is done by the underlying hardware of the network interface.
I guess, you captured the ARP requests via wireshark/tcpdump, so you don't see the modifications of the packets done by the hardware interface.

**Comment by arup42** [comment]
Thanks. That makes sense. I was observing the packets using tcpdump at the sender. If I observe them using tcpdump at the receiver or on a third party, I see the padding that has been added by the network interface on the sender.
