### ISSUE TITLE
Memory allocations inside parser.DecodeLayers

### ISSUE THREAD

**Issue by JustinAzoff** [google/gopacket#369]
Hi!

I've been using this method to decode packet headers:

	var eth layers.Ethernet
	var dot1q layers.Dot1Q
	var ip4 layers.IPv4
	var ip6 layers.IPv6
	var tcp layers.TCP
	var udp layers.UDP
	parser := gopacket.NewDecodingLayerParser(layers.LayerTypeEthernet, &eth, &dot1q, &ip4, &ip6, &tcp, &udp)
	decoded := []gopacket.LayerType{}
	for i := 0; i < 1000000; i++ {
		packetData, _, err := handle.ZeroCopyReadPacketData()
		if err == io.EOF {
			break
		} else if err != nil {
			log.Fatal(err)
		}

		err = parser.DecodeLayers(packetData, &decoded)

with #367 fixed I notice that DecodeLayers is a allocating memory in the error path due to errors like

```
2017/10/10 13:00:36 No decoder for layer type ARP
2017/10/10 13:00:36 No decoder for layer type Payload
```

The unsupported error does

```
func (e UnsupportedLayerType) Error() string {
    return fmt.Sprintf("No decoder for layer type %v", LayerType(e))
}
```

changing

            return UnsupportedLayerType(typ)

to just return `nil` removes all the allocations.  I can bpf filter out arp, and add a `Payload` to my layers, but then I get errors about layers like `DNS`.

I'm not sure what the approach should be here.. Caching the error values once in `init` could work, but in my case this isn't even really an error... I only want the ip/{tcp,udp} header decoded and then to stop. 

maybe a `l.IgnoreUnsupported` flag would work here?

**Comment by gconnell** [comment]
I'd definitely be okay with an IgnoreUnsupported flag, if that works for you.

**Comment by JustinAzoff** [comment]
![screen shot 2017-10-10 at 1 29 28 pm](https://user-images.githubusercontent.com/65812/31400887-1a7b2e4a-adbf-11e7-9fea-f3c030a9fa23.png)

#367 + this fix will get the memory allocations of my app down to almost nothing.

**Comment by gconnell** [comment]
Give https://github.com/google/gopacket/pull/370 a try.

**Comment by JustinAzoff** [comment]
That looks like it will work.
