### ISSUE TITLE
modbus and dnp3

### ISSUE THREAD

**Issue by vgraveto** [google/gopacket#374]
Hello,

Is anyone developing a layer for SCADA protocols like modbus or DNP3?

Regards,
Vitor Graveto

**Comment by gconnell** [comment]
You! :D 

Haven't heard of any work in this space yet, but I'd love to receive some if you're interested.

**Comment by lhausermann** [comment]
Hi @vgraveto @gconnell 

That's what we do and have at sentryo.
Contact me at laurent [dot] hausermann [at] sentryo [dot] net

**Comment by reza-ebrahimi** [comment]
@lhausermann if you have a previous experience on golang packet processing, please tell about that, is that reasonable for a high performance or hard real-time use cases?

**Comment by lhausermann** [comment]
Hi @reza-ebrahimi . Well I am the cofounder of Sentryo (https://www.sentryo.net) we have many DPI layers for industrial protocols . Send me an email at laurent at sentryo.net
