### ISSUE TITLE
Enum data takes 18MB of memory

### ISSUE THREAD

**Issue by dlespiau** [google/gopacket#376]
The EnumMetadata objects take about 18MB of memory as about 133k strings and functions are created in https://github.com/google/gopacket/blob/master/layers/enums.go#L388.

It'd be nice to turn some of this into functions instead of heap data.

![screenshot from 2017-10-21 23-51-47](https://user-images.githubusercontent.com/7986/31856538-486512f8-b6bb-11e7-8fe3-31d413e4aa41.png)

**Comment by gconnell** [comment]
It's been a request in the past, but unfortunately it seems impossible to handle this without seriously breaking backwards compatibility.  If you have any thoughts on the best way to transition this, though, I'd be happy to hear them.

**Comment by gconnell** [comment]
Actually, it seems eminently possible to make this data at least DATA-section instead of heap, by making the strings all constant.  Could save on startup time, too... let me take a quick look.

**Comment by dlespiau** [comment]
Maybe the EnumMetadata entries, in say EthernetTypeMetadata to make things concrete, for ether types without a handler could remain uninitialised. Then, `EthernetType.Decode()` could test whether this EthernetTypeMetadata[a].DecodeWith is nil and provide the default behaviour that is currently assigned to every entry in `init()`.

Of course, strictly speaking, this break compatibility as `EthernetTypeMetadata[i]` can now contain uninitialized data.

A good thing would be to know how awful it would be if EthernetTypeMetadata were to be hidden in future versions, provided there's a new way for people to override the decoders.

**Comment by gconnell** [comment]
See #377 to see if that helps things out.

**Comment by dlespiau** [comment]
With #377 merged we can close this, thanks for the extremely quick PR!
