### ISSUE TITLE
Why does the RST send out?

### ISSUE THREAD

**Issue by jianjin** [google/gopacket#391]
I intend to use gopacket to do TCP 3-way handshake. But when I send out SYN successfully, after SYN+ACK back from the remote side, client-side send back RST.

I think the RST is sent out by operating system's TCP/IP stack because the SYN is not known by OS. Is my theory correct? If that is true, seems gopacket is more useful for capturing.

**Comment by gconnell** [comment]
That is correct: on a normal interface, GoPacket will send the SYN, but the OS won't know about it and won't update the TCP state tables accordingly, so according to the OS it's just getting a SYN/ACK from the remote IP without any TCP connection in place, and it'll ignore it.

If you do want to do actual TCP handshakes with GoPacket, you'll need to do them in such a way that the kernel doesn't think it should be handling them at all.  One alternative is to use an IP that's not directly associated with your interface, but that routes to it (for example, pick an unused static IP within your layer2 domain).
