### ISSUE TITLE
how i can get only TimeStamp Value

### ISSUE THREAD

**Issue by SaifSalah** [google/gopacket#393]
hi today i used goapcket and i have issue:

how i can get only Timestamp value from tcp.Options.. i make for loop on it and have 3 key and value 0 1 2, but when i chosse [2] i got error slice out of range

thanks

**Comment by gconnell** [comment]
Note that many TCP packets don't have the timestamp option set in the
packet.  If you'd like to iterate over all options, use:

for _, opt := range tcp.Options {
  ...
}

If you'd like to get the capture timestamp for a packet, use:

packet.Metadata().Timestamp

**Comment by SaifSalah** [comment]
srry i think you don't understand me what  i mean


this my code

`	tcpLayer := packet.Layer(layers.LayerTypeTCP)
		if tcpLayer != nil {
			tcp, _ := tcpLayer.(*layers.TCP)
			fmt.Println("SrcPort: ", tcp.SrcPort)
			fmt.Println()
			for i,val  := range tcp.Options {

				fmt.Println("Key: ",i,"Value :", val)
			}
		} else {
			fmt.Println("NULL.")
		}`




this my result from capture

Key:  0 Value : TCPOption(NOP:)
Key:  1 Value : TCPOption(NOP:)
Key:  2 Value : TCPOption(Timestamps:743883130/749163709 0x2c56c17a2ca754bd)

i want get only this value ( TCPOption(Timestamps:743883130/749163709 0x2c56c17a2ca754bd )

**Comment by SaifSalah** [comment]
thank you, i solved issue xD

for i,_  := range tcp.Options {

				if i == 2{

					fmt.Println(tcp.Options[i])
				}


			}

<3
