### ISSUE TITLE
Suggest switching to alternate content for /pcap/test_ethernet.pcap

### ISSUE THREAD

**Issue by swinslow** [google/gopacket#399]
In looking at the licenses for gopacket, I noticed that the test capture file at /pcap/test_ethernet.pcap contains content with a CC-BY-NC-2.5 license, which is the Creative Commons Attribution-NonCommercial 2.5 License.

Would it be possible to replace this with an alternative test capture file that doesn't contain content subject to a noncommercial-only license?

**Comment by gconnell** [comment]
Oh yeah, sure thing.  I just curl'd xkcd to generate that file :P

**Comment by swinslow** [comment]
I thought it looked like xkcd. =) Thanks!
