### ISSUE TITLE
make an option to compile libraries statically

### ISSUE THREAD

**Issue by blshkv** [google/gopacket#424]
there is an issue with bettercap (its binary distribution) and an author decided to fork gopacket in order to compile it with libraries (libpcap in particular) statically. 

Perhaps, you could make this option here instead.

For more details, see the following discussion:
https://github.com/bettercap/bettercap/issues/101

**Comment by evilsocket** [comment]
Super interested in having this as a compilation option so I can drop my fork and keep using the main one ^_^

**Comment by negbie** [comment]
Why not simply use musl?

# Make a static 64 bit binary:

# docker run --rm=true -itv $PWD:/mnt alpine:3.7 /mnt/build_static.sh

# Make a static 32 bit binary:

# docker run --rm=true -itv $PWD:/mnt i386/alpine:3.7 /mnt/build_static.sh

set -ex

apk update

apk add linux-headers musl-dev gcc go libpcap-dev ca-certificates git

mkdir /go

export GOPATH=/go

mkdir -p /go/src/github.com/yourrepo

mkdir -p /mnt/out

cp -a /mnt /go/src/github.com/yourrepo/yourtool

cd /go/src/github.com/yourrepo/yourtool

rm -f yourtool*

go get -v ./ ./

go build --ldflags '-linkmode external -extldflags "-static -s -w"' -v ./

cp ./yourtool /mnt/out/

**Comment by evilsocket** [comment]
@negbie maybe I'm mistaken here, but the problem is not how we build our tool, but how gopacket is built. Given there're no conditional compilation flags (that I'm aware of), the only way to have a static build is to patch `pcap/pcap.go` cgo directives. I can trigger a static build for my tool, but regardless gopacket will link libpcap.so instead of libpcap.a.

**Comment by evilsocket** [comment]
@negbie yes that is the idea ... I'm not familiar enough with Docker so i'm afraid your instructions are not very clear to me then :)

**Comment by evilsocket** [comment]
@negbie dude you saved my day!

**Comment by negbie** [comment]
Mby I should provide a better explanation. The key here isn't the use of docker, its to circumvent the lack of glibc's static linking by using musl which comes out of the box in alpine linux. So the quickest way is to use the docker alpine container and install there some stuff we need for the static linking. So create a bash script build_static.sh with:

#!/bin/sh
set -ex
apk update
apk add linux-headers musl-dev gcc go libpcap-dev ca-certificates git

mkdir /go
export GOPATH=/go
mkdir -p /go/src/github.com/yourrepo
mkdir -p /mnt/out
cp -a /mnt /go/src/github.com/yourrepo/yourtool
cd /go/src/github.com/yourrepo/yourtool
rm -f yourtool*
go get -v ./ ./
go build --ldflags '-linkmode external -extldflags "-static -s -w"' -v ./
cp ./yourtool /mnt/out/

Inside the same folder run 
docker run --rm=true -itv $PWD:/mnt alpine:3.7 /mnt/build_static.sh

**Comment by blshkv** [comment]
@evilsocket so can close the bug? It looks like you can compile it in and this is an alternative solution

**Comment by evilsocket** [comment]
@blshkv Right now I'm using [this](https://github.com/bettercap/bettercap/blob/master/build.sh#L69) ... the method mentioned by @negbie doesn't work for every OS as you can see on the build.sh script, but I guess that's not related to this issue. We dropped our fork of gopacket for the time being ... so I guess, yes? ( Needless to say, any suggestion on how to improve that build.sh is more than welcome :P)

**Comment by blshkv** [comment]
Ok, great! I don't have much time but was happy to help a bit. Thank you all for your work!

**Comment by blshkv** [comment]
Guys, I have a question. The latest version of bettercap (v2.2) is compiled statically and depends on libpcap for some reason. I actually expected to have an option to compile gopacket with shared libraries so that bettercap won't require libpcap.

Is any way of doing it?

**Comment by evilsocket** [comment]
@blshkv no, 2.2 is not compiled statically on every platform, linux/amd64 build is not static for instance and will require `libpcap.so` to be present in the system.

**Comment by blshkv** [comment]
sorry, I wasn't clear. bettercap is compiled with gopacket and the outcome is one big binary.
But I'm new to Go and did not realised that this is a language limitation.

Here is the background. At pentoo, we create ebuilds which should list down dependency. I have created a separate ebuild for gopacket which depends on libpcap (and pf_ring optionally). However, it was flagged that bettercap should also depend on libpcap since its binary requires it.

I guess there is nothing we can do here.
