### ISSUE TITLE
LLDP doesn't satisfy SerializableLayer interface?

### ISSUE THREAD

**Issue by irfabid** [google/gopacket#448]
Am I missing something or LinkLayerDiscovery needs to satisfy SerializableLayer interface but doesn't do it currently?
I would be happy to contribute to this if that's the case.

**Comment by gconnell** [comment]
You are not missing anything :)

SerializableLayer and DecodingLayer are both optional interfaces that layer writers can choose to implement or not when they initially contribute, to lower the barrier for initial contribution of layer types.

If you are interested in contributing, we'd love to receive your work!  And let us know if there's any questions you have along the way.

**Comment by baba147** [comment]
Hi,

I made a couple of non-breaking changes to allow LinkLayerDiscovery to serialize properly.

1. Most obvious, now LinkLayerDiscovery satisfies SerializableLayer interface
2. A new interface called LLDPSerializableTLV which ensures that each TLV is responsible for serializing itself
3. As an example, ChassisID now statisfies this new interface (I will add code for more TLVs, this is just a start).

Benefit of having TLVs serialize themselves is that any custom/org-specific TLV can easily be added. It just has to satisfy the new interface.

The unexported serializeTLV function is not in use. I will probably remove it later.

**Regarding pull requests:** Should I wait till completion for PR? Or PR can be created with incomplete work for reviewing purposes?

**Comment by gconnell** [comment]
Feel free to send an incomplete PR out for comments :)
