### ISSUE TITLE
NewPacket vs layers.*: NewPacket has low performance

### ISSUE THREAD

**Issue by styleex** [google/gopacket#457]
I wrote two programs that receive traffic from af_packet and decode the package and they have very different performance.
The first program uses gopacket.NewPacket, and the second one directly uses the layers package.

When using NewPacket, the performance reaches a maximum of 200 mbit/s.
When using the layers - 4-5 gbit/s package.

Why this can happen?

To generate traffic, I use linux pktgen (https://www.kernel.org/doc/Documentation/networking/pktgen.txt).

First program (up to 200 mbit/s):
```
package main

import (
	"github.com/google/gopacket/afpacket"
	"log"
	"time"
	"sync/atomic"
	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
)

var rx int64

func printRxStats() {
	t := time.NewTicker(1 * time.Second)

	lastTime := time.Now()
	var lastValue int64 = 0
	for _ = range t.C {
		now := time.Now()
		tmp := rx
		delta := now.Sub(lastTime).Seconds()
		if delta == 0 {
			continue
		}

		d := float64(tmp - lastValue) / delta
		log.Printf("%.2f MBit/s", 8*d / (1024*1024))

		lastValue = tmp
		lastTime = now
	}
}

func main() {
	inputAFpacket, err := afpacket.NewTPacket(afpacket.OptInterface("ens10"))
	if err != nil {
		log.Fatal(err)
	}
	defer inputAFpacket.Close()

	go printRxStats()

	for {
		pkt, _, err := inputAFpacket.ZeroCopyReadPacketData()
		if err != nil {
			log.Fatal(err)
		}

		atomic.AddInt64(&rx, int64(len(pkt)))

		packet := gopacket.NewPacket(pkt, layers.LayerTypeEthernet, gopacket.NoCopy)
		if packet == nil {
			// todo
		}
	}
}
```

Second (up to 4-5 gbit/s):
```
package main

import (
	"github.com/google/gopacket/afpacket"
	"log"
	"time"
	"sync/atomic"
	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
)

var rx int64

func printRxStats() {
	t := time.NewTicker(1 * time.Second)

	lastTime := time.Now()
	var lastValue int64 = 0
	for _ = range t.C {
		now := time.Now()
		tmp := rx
		delta := now.Sub(lastTime).Seconds()
		if delta == 0 {
			continue
		}

		d := float64(tmp - lastValue) / delta
		log.Printf("%.2f MBit/s", 8*d / (1024*1024))

		lastValue = tmp
		lastTime = now
	}
}

func main() {
	inputAFpacket, err := afpacket.NewTPacket(afpacket.OptInterface("ens10"))
	if err != nil {
		log.Fatal(err)
	}
	defer inputAFpacket.Close()

	go printRxStats()

	for {
		pkt, _, err := inputAFpacket.ZeroCopyReadPacketData()
		if err != nil {
			log.Fatal(err)
		}

		atomic.AddInt64(&rx, int64(len(pkt)))

		ether := layers.Ethernet{}
		if err = ether.DecodeFromBytes(pkt, gopacket.NilDecodeFeedback); err != nil {
			log.Println(err)
		}
		if ether.EthernetType != layers.EthernetTypeIPv4 {
			continue
		}
		ipv44 := layers.IPv4{}
		if err = ipv44.DecodeFromBytes(ether.Payload, gopacket.NilDecodeFeedback); err != nil {
			log.Println(err)
			continue
		}
		udpp := layers.UDP{}
		if err = udpp.DecodeFromBytes(ipv44.Payload, gopacket.NilDecodeFeedback); err != nil {
			log.Println(err)
		}
	}
}
```

**Comment by gconnell** [comment]
Yep, this makes perfect sense.

The issue is that NewPacket has to make layers on the heap, while your second job makes layers on the stack.  Making layers on the heap requires lots of work malloc'ing (and then free'ing via GC) the layers, including locking so multiple threads can (potentially) interact with the heap, etc.  Making layers on the stack is MUCH cheaper, as done by your second program.

The short story is that NewPacket is easy/slow, and DecodeFromBytes is hard/fast.  If you do want fast, instead of calling each DecodeFromBytes I recommend using DecodingLayerParser.  See https://godoc.org/github.com/google/gopacket#hdr-Fast_Decoding_With_DecodingLayerParser for a discussion of this exact performance gain/hit.

**Comment by styleex** [comment]
Thanks for the explanation! I missed this section of the documentation :(

**Comment by gconnell** [comment]
No worries, always feel free to send questions!

There's a lot of documentation, so sometime things get buried :)
