### ISSUE TITLE
Flow control in a new decoder

### ISSUE THREAD

**Issue by vgraveto** [google/gopacket#465]
I am developing a new layer decoder for an application layer protocol.
Request and response have different footprints, how can I check the flow within my decoder?
It depends on the outer layer info, how can I reach it?

**Comment by florianl** [comment]
Hi @vgraveto 
can you share the information, on which protocol you are working on? Maybe having a look at the implementation of  ICMP might help you.

florian

**Comment by vgraveto** [comment]
Thanks @florianl 
Attached you can find my code, the protocol is ModbusTCP, that is encapsulated in TCP and to check if the PDU is a request or a response I need to know if the dst port is 502 or the src port is 502.

How can I get that information from the TCP layer within me ModbusTCP layer? Or how should I workaround this problem.

**Comment by florianl** [comment]
I just had a quick look into the wikipedia article of ModbusTCP, as I am not able to get the specification at [1]. But in general I would not rely on checking the src or dst port, to differentiate between a request and a response. Otherwise it would be hard to distinguish on Modbus variants based on serial communication protocols.

As Modbus is a Master/Slave protocol, why do you want to differentiate on the ModbusTCP protocol implementation layer between these two?

[1] https://www.vde-verlag.de/iec-normen/218642/iec-61784-5-15-2010.html

**Comment by vgraveto** [comment]
@florianl thanks for your help

My problem is not with the protocols.
I would like to know how to implement de layers well, according to gopacket design.

Modbus was developed to communicate over a serial, normally RS485, connection so the packets do not include any information to distinguish between a _request_ and a r_esponse_, [see](http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf). ModbusTCP was later developed to encapsulate legacy Modbus over a TCP connection, [see](http://www.modbus.org/docs/Modbus_Messaging_Implementation_Guide_V1_0b.pdf).
So my idea is to implement ModbusTCP as a layer and then on function NextLayerType do something like:
`
func (t *ModbusTCP) NextLayerType() gopacket.LayerType {

        id t.PDU==mb_req_pdu {
             return LayerTypeModbusRequest
        }
	return LayerTypeModbusResponse
}
`
So that a _response_ or a _request_ are seen as different layer types ModbusRequest and ModbusResponse. I think this is the best interpretation of the protocolos.

If we peak the inner ModbusTCP without knowing the external TCP header, it is impossible to decode the Modbus payload (PDU) that it contains, as far was I have knowledge. If I use only one layer for all the Modbus decoding the problem would be the same.

So my question is about then proper design pattern to overcome this specificity of the protocol in gopacket. My skills on Go are limited to my about one year experience, but I really love the language.

Just one more detail, in order to detect ModbusTCP layer I added port 502 to ports.go like:
`var tcpPortLayerType = [65536]gopacket.LayerType{

	53: LayerTypeDNS,
	502: LayerTypeModbusTCP,
}`

Is that the way to do it?

**Comment by florianl** [comment]
I would recommend to implement and provide common parts of the protocol in the ModbusTCP layer and declare everything else as payload. The client needs it's state, either Master or Slave, and handle the payload accordingly.

Don't forget to register your layer in "layers/layertypes.go".

**Comment by vgraveto** [comment]
Yes @florianl , that is my intention:

1. Use _ModbusTCP_ layer to decode de common parts of the protocol - that is done (just missing my problem that is how to distinguish a request from a response)
2. Use a new _ModbusRequest_ layer to decode the payload in case of a request
3. Use a new _ModbusResponse_ layer to decode the payload in case of a response

So **the problem is how to decide** in the function _NextLayerType_ of _ModbusTCP_ layer the correct decoder for the payload - this decision needs to be based on the surrounding TCP layer.

I have been analysing several files of the gopacket and layers implementation and I am not able to figure out how to solve this issue. 

I had already registed my layers on  "layers/layertypes.go".

**Comment by florianl** [comment]
Hi @vgraveto 
I see your point. And still, I think, using `LayerTypePayload` as `NextLayerType` for ModbusTCP is the best way to go. The payload of a request/response are application-level dependent [1]. Only the application knows, if it is in master/slave mode.

[1] https://godoc.org/github.com/google/gopacket#LayerTypePayload

**Comment by vgraveto** [comment]
Hi @florianl 

So if I understand your point I can still create the layers _ModbusRequest_ and _ModbusResponse_ but they will only be user on the payload at the application level if required by the application. So when decoding a packet with `packet := gopacket.NewPacket(myPacketData, layers.LayerTypeEthernet, gopacket.Default)
` it will decode _ModbusTCP_ layer and stop.

But I am still missing a point, if I do not insert the port at _tcpPortLayerType_ how will the _ModbusTCP_ be detected?
For example to decode the DNS layer it is also needed to include the port number on _ports.go_, or not?

**Comment by florianl** [comment]
Hi @vgraveto 
in `layers/ports.go` you can do a mapping of well known protocols and their implementation. And yes - this might also include 502 and ModbusTCP. But you don't need to.

e.g.:
Someone passes only the tcp payload to your ModbusTCP implementaition. That is a completely valid use-case and your implementation should still be able to decode this payload and handle it as ModbusTCP data.

**Comment by vgraveto** [comment]
Hi @florianl ,

Sorry to insist, but maybe that is my problem.
The ModbusTCP has a 7 bytes header the MBAP. Only the 3rd and 4th byte should be 0x0000 to specify the Modbus protocol. All the following bytes should be the ModbusTCP payload (the Modbus layer packet either request or response). Plenty of byte sequences satisfy this and are not well formed.

My question is on the use case of someone passing an IP payload (that contains ModbusTCP and Modbus inside the TCP payload) to the TCP decoder how is it going to find that Modbus content?

I am surly missing some thing.

**Comment by florianl** [comment]
Hi @vgraveto 
can you provide example data? Can you also provide  a code example, how it looks like for a different protocol? e.g. NTP in UDP maybe?

**Comment by vgraveto** [comment]
Hi @florianl 

I am using pcapdump in order to test my implementation. I am getting the following results when input is the file with 6 packets (just remove the txt extension of the cap file):
`PACKET: 66 bytes, wire length 66 cap length 66 @ 2016-05-10 14:32:26.472302 +0100 WEST
Starting to read packets
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..52..] SrcMAC=00:50:56:bf:41:d5 DstMAC=00:0d:22:04:d1:d1 EthernetType=IPv4 Length=0}
- Layer 2 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=18480 Flags=DF FragOffset=0 TTL=128 Protocol=TCP Checksum=12285 SrcIP=172.27.21.61 DstIP=172.27.21.35 Options=[] Padding=[]}
- Layer 3 (32 bytes) = TCP	{Contents=[..32..] Payload=[] SrcPort=50356 DstPort=502(mbap) Seq=3659548812 Ack=0 DataOffset=8 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=8192 Checksum=58151 Urgent=0 Options=[..6..] Padding=[]}

PACKET: 60 bytes, wire length 60 cap length 60 @ 2016-05-10 14:32:26.472311 +0100 WEST
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..46..] SrcMAC=00:0d:22:04:d1:d1 DstMAC=00:50:56:bf:41:d5 EthernetType=IPv4 Length=0}
- Layer 2 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..24..] Version=4 IHL=5 TOS=0 Length=44 Id=35217 Flags=DF FragOffset=0 TTL=128 Protocol=TCP Checksum=61091 SrcIP=172.27.21.35 DstIP=172.27.21.61 Options=[] Padding=[]}
- Layer 3 (24 bytes) = TCP	{Contents=[..24..] Payload=[] SrcPort=502(mbap) DstPort=50356 Seq=3192682669 Ack=3659548813 DataOffset=6 FIN=false SYN=true RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=1024 Checksum=62176 Urgent=0 Options=[TCPOption(MSS:1024 0x0400)] Padding=[]}

PACKET: 60 bytes, wire length 60 cap length 60 @ 2016-05-10 14:32:26.472399 +0100 WEST
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..46..] SrcMAC=00:50:56:bf:41:d5 DstMAC=00:0d:22:04:d1:d1 EthernetType=IPv4 Length=0}
- Layer 2 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..20..] Version=4 IHL=5 TOS=0 Length=40 Id=18481 Flags=DF FragOffset=0 TTL=128 Protocol=TCP Checksum=12296 SrcIP=172.27.21.61 DstIP=172.27.21.35 Options=[] Padding=[]}
- Layer 3 (20 bytes) = TCP	{Contents=[..20..] Payload=[] SrcPort=50356 DstPort=502(mbap) Seq=3659548813 Ack=3192682670 DataOffset=5 FIN=false SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=64512 Checksum=4329 Urgent=0 Options=[] Padding=[]}

PACKET: 66 bytes, wire length 66 cap length 66 @ 2016-05-10 14:32:26.47249 +0100 WEST
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..52..] SrcMAC=00:50:56:bf:41:d5 DstMAC=00:0d:22:04:d1:d1 EthernetType=IPv4 Length=0}
- Layer 2 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=18482 Flags=DF FragOffset=0 TTL=128 Protocol=TCP Checksum=12283 SrcIP=172.27.21.61 DstIP=172.27.21.35 Options=[] Padding=[]}
- Layer 3 (20 bytes) = TCP	{Contents=[..20..] Payload=[..12..] SrcPort=50356 DstPort=502(mbap) Seq=3659548813 Ack=3192682670 DataOffset=5 FIN=false SYN=false RST=false PSH=true ACK=true URG=false ECE=false CWR=false NS=false Window=64512 Checksum=58809 Urgent=0 Options=[] Padding=[]}
- Layer 4 (07 bytes) = ModbusTCP	{Contents=[..7..] Payload=[..5..] TransactionIdentifier=10625 ProtocolIdentifier=0 Length=6 UnitIdentifier=1 PDU=0}
- Layer 5 (05 bytes) = Modbus	{Contents=[..5..] Payload=[]}

PACKET: 60 bytes, wire length 60 cap length 60 @ 2016-05-10 14:32:26.47375 +0100 WEST
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..46..] SrcMAC=00:0d:22:04:d1:d1 DstMAC=00:50:56:bf:41:d5 EthernetType=IPv4 Length=0}
- Layer 2 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..20..] Version=4 IHL=5 TOS=0 Length=40 Id=35218 Flags=DF FragOffset=0 TTL=128 Protocol=TCP Checksum=61094 SrcIP=172.27.21.35 DstIP=172.27.21.61 Options=[] Padding=[]}
- Layer 3 (20 bytes) = TCP	{Contents=[..20..] Payload=[] SrcPort=502(mbap) DstPort=50356 Seq=3192682670 Ack=3659548825 DataOffset=5 FIN=false SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=1024 Checksum=2270 Urgent=0 Options=[] Padding=[]}

PACKET: 95 bytes, wire length 95 cap length 95 @ 2016-05-10 14:32:26.47384 +0100 WEST
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..81..] SrcMAC=00:0d:22:04:d1:d1 DstMAC=00:50:56:bf:41:d5 EthernetType=IPv4 Length=0}
- Layer 2 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..61..] Version=4 IHL=5 TOS=0 Length=81 Id=35219 Flags=DF FragOffset=0 TTL=128 Protocol=TCP Checksum=61052 SrcIP=172.27.21.35 DstIP=172.27.21.61 Options=[] Padding=[]}
- Layer 3 (20 bytes) = TCP	{Contents=[..20..] Payload=[..41..] SrcPort=502(mbap) DstPort=50356 Seq=3192682670 Ack=3659548825 DataOffset=5 FIN=false SYN=false RST=false PSH=true ACK=true URG=false ECE=false CWR=false NS=false Window=1024 Checksum=16204 Urgent=0 Options=[] Padding=[]}
- Layer 4 (07 bytes) = ModbusTCP	{Contents=[..7..] Payload=[..34..] TransactionIdentifier=10625 ProtocolIdentifier=0 Length=35 UnitIdentifier=1 PDU=0}
- Layer 5 (34 bytes) = Modbus	{Contents=[..34..] Payload=[]}
[Modbus1.pcap.txt](https://github.com/google/gopacket/files/2105563/Modbus1.pcap.txt)
`
The main issue is that in 4th packet we have a request and on 6th packet we have a response. So how can ModbusTCP distinguish between them for layer 5 to contain a ModbusRequest or ModbusResponse as NextLayer. Allowing the proper decoding of that 5th layer as I am doing on the 4th layer for ModbusTCP.

I added to layers/ports.go the 502 port to detect the ModbusTCP and I have used Modbus layer as the NextLayer for it. 

Thanks for your interest and support.

**Comment by florianl** [comment]
For me even wireshark does not make a difference, between a request and a response.

So I would go with:
```
type ModbusTCP struct {
	BaseLayer
        TransactionIdentifier
        ProtocolIdentifier
        Length
        UnitIdentifier
}
```
Everything else will be the payload of ModbusTCP.

I'm looking forward for your pull request on this repo.

**Comment by vgraveto** [comment]
Hi @florianl ,

I already created a pull request  #477.
I also already added both google and my GitHub emails to the CLA.
The bot is not finding them!

**Comment by vgraveto** [comment]
The problem of PR #477 is solved, now waiting ...

**Comment by vgraveto** [comment]
ModbusTCP already merged to master
