### ISSUE TITLE
reassembly: Flush might close half connection and cause data loss.

### ISSUE THREAD

**Issue by noibar** [google/gopacket#487]
If assembler.FlushWithOptions is called, and one of the halfConnection is seen only before the specified time, half of the connection is closed. If another packet that belongs to this halfConnection is received, the stream pool returns the main connection, with half connection closed, and the data is discarded without and error or log message. 

```go:
 func (a *Assembler) AssembleWithContext(netFlow gopacket.Flow, t *layers.TCP, ac AssemblerContext) {
    // ...

    if half.closed {
        return
    }

    // ...
}
```

**Comment by lhausermann** [comment]
Great @noibar , second bug fixed into @sentryo contribution (defrag and reassembly)
Hey, we are hiring by the way ;-)
