### ISSUE TITLE
IgnoreUnsupported option in DecodeLayerParserOptions

### ISSUE THREAD

**Issue by gkodali-zededa** [google/gopacket#525]
This not a bug report but a question that I had. I'm filling a bug report since I couldn't find another way of reaching out top the wider forum.

https://github.com/google/gopacket/commit/0e1d984258d7af797a140444a3d135389c7ac389

The commit above adds support for something I would like to use. But, this commit was made after the last release v1.1.4 on the September of 2017. There were no further releases done after v1.1.14.

I would like to know when a new release can be expected.

PS: I do not want to directly use master branch in my production.

**Comment by gconnell** [comment]
Hey, sure thing.

I mostly do a release when someone asks me to.  I'll consider this you asking me to ;)

Release v1.1.15 pushed.

**Comment by gkodali-zededa** [comment]
Thank you Graeme!!
