### ISSUE TITLE
is reassembly uni-directional ? [question]

### ISSUE THREAD

**Issue by jandos** [google/gopacket#554]
Hello,
First of all thanks for the great work on this project!

My question is about the reassembly package (which looks like a newer version of tcpassembly).
The doc for reassembly states that it implements **uni-directional** TCP reassembly.
However, from what I see in the code, and in one of the commit messages (cb42ef4a2ea84dcd52e315e033902eb651559e3a), it actually does full **bidirectional** reassembly.

So, is it uni or bi-directional ?

Thanks.

**Comment by gconnell** [comment]
To close the loop on this in case anyone else sees and has the same question:

tcpassembly/ is (as you correctly mentioned) old and unidirectional
reassembly/ is new, and is bidirectional.  The ScatterGather object that's passed into it contains "direction" in the info which says whether the specific data is A->B or B->A
