### ISSUE TITLE
Where to place pcap.h file on Windows?

### ISSUE THREAD

**Issue by vaastav** [google/gopacket#575]
Hi,
I am trying to use gopacket on windows but I get the following error:

# github.com/google/gopacket/pcap
C:\Go-Path\src\github.com\google\gopacket\pcap\pcap.go:22:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.

I know the issue is that I don't have libpcap installed. I found winpcap as an alternative which can provide the relevant header and source files. I was just confused as to where to place these files in relation to gopacket so that I have a successful compilation?

Thanks!!

**Comment by notti** [comment]
At the moment you have two possibilities:

1. Try out pull request #568 with which you don't need any headers (therefore no winpcap sdk).
2. Or put the winpcap sdk into C:/WpdPack/ as was used in:
https://github.com/google/gopacket/blob/3c037fb4650eaecb208dfa07c0bf4c7e3bb3b7be/pcap/pcap.go#L18-L20

If you try 1. please report success or failure to the pull request. Thanks.

**Comment by vaastav** [comment]
Hmm, if I use option 2 then I am still getting the following error : 
exit status 3221225781

Seems like I am missing a dll....
Although there is wpcap.lib exists in the path specified in LDFLAGS

I haven't tried option 1 yet but I will let you know how it turns out for me if and when I try it.

**Comment by notti** [comment]
Oh sorry forgot; For 64 bit Windows you need to follow https://stackoverflow.com/questions/38047858/compile-gopacket-on-windows-64bit

**Comment by notti** [comment]
#568 got merged. Does it work for you?

**Comment by notti** [comment]
Closed due to inactivity and being out of date (cgo is not needed any longer on windows)
