### ISSUE TITLE
Unresolved type '_Ctype_struct_bpf_program

### ISSUE THREAD

**Issue by ItsFunny** [google/gopacket#586]
i dont know whats wrong with it ,pcap.go L 211 just say this 
OS:
Windows 10

**Comment by ItsFunny** [comment]
things didnt go well  finally, i still got the pro,its sad :(

**Comment by gconnell** [comment]
Hey, do you happen to know the version of winpcap that you originally used?  @notti wondering if this could be due to the recent switch to DLL stuff.

**Comment by gconnell** [comment]
Oh, never mind, it looks like that pull (#568) isn't merged yet.
