### ISSUE TITLE
Implement Dot11InformationElement SerializableLayer interface

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gopacket#59]
```
What steps will reproduce the problem?
1. Parse Dot11 information elements
2. Serialize the layers into binary sequence
3. SerializableLayer is not implemented yet

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `Hiroaki.Kawai@gmail.com` on 16 Mar 2015 at 9:21

Attachments:
- [0001-Implement-Dot11InformationElement-SerializableLayer.patch](https://storage.googleapis.com/google-code-attachments/gopacket/issue-59/comment-0/0001-Implement-Dot11InformationElement-SerializableLayer.patch)

**Comment by notti** [comment]
This patch was included in 5852d282e9df7f35cb8a315f9eca391c81c10e02
