### ISSUE TITLE
Weird build error when compiling my project with Raspberry Pi

### ISSUE THREAD

**Issue by tomruk** [google/gopacket#601]
I have  a Raspberry Pi 3, and i when i try to compile my project (https://github.com/tomruk/oraj) with my laptop which has amd64 processor, it compiles successfully, but when i try it with Raspberry Pi it gives me the following error:

```
# github.com/tomruk/oraj/vendor/github.com/google/gopacket/pcap
vendor/github.com/google/gopacket/pcap/pcap_unix.go:373:16: type [1073741824]_Ctype_int larger than address space
vendor/github.com/google/gopacket/pcap/pcap_unix.go:373:16: type [1073741824]_Ctype_int too large
vendor/github.com/google/gopacket/pcap/pcap_unix.go:619:18: type [1073741824]_Ctype_int larger than address space
vendor/github.com/google/gopacket/pcap/pcap_unix.go:619:18: type [1073741824]_Ctype_int too large
```

It seems like it is a problem with the variable size

### Info

My go version is: 1.11.4
Also i updated the gopacket to the latest version

**Comment by notti** [comment]
Latest commit in master should fix this problem. If it does not, please reopen the issue.

**Comment by tomruk** [comment]
Thank you @notti! It worked, you saved my day
