### ISSUE TITLE
Is FlushWithOptions concurrent save????

### ISSUE THREAD

**Issue by schmilmo** [google/gopacket#603]
Hi,

I tried to run FlushWithOption in a separate routine so that the main routine could run without interruption.
I got multiple panic errors.
Is FlushWithOption concurrent save??

Samuel

**Comment by gconnell** [comment]
Assemblers are never safe for concurrency, see https://godoc.org/github.com/google/gopacket/reassembly#Assembler

Each assembler should be used only by a single goroutine.  If assembling across multiple goroutines, use multiple assemblers.

**Comment by schmilmo** [comment]
According to the following they are

https://github.com/google/gopacket/blob/master/reassembly/tcpassembly.go#L14
// The Assembler uses a user-supplied
// StreamFactory to create a user-defined Stream interface, then passes packet
// data in stream order to that object.  A concurrency-safe StreamPool keeps
// track of all current Streams being reassembled, so multiple Assemblers may
// run at once to assemble packets while taking advantage of multiple cores.

**Comment by gconnell** [comment]
The StreamPool is safe for concurrency, but the Assembler is not.  So, multiple different Assemblers can use a single shared StreamPool from multiple goroutines, but each Assembler must be used only by a single GoRoutine.
