### ISSUE TITLE
[Question] Build with npcap embedded on windows?

### ISSUE THREAD

**Issue by JulienTant** [google/gopacket#615]
Hi,

Thanks you so much for that package it is so nice.

I'm building a windows application that uses gopacket, and I was wondering if there was a way for me to distribute a binary file without requiring the final user to install npcap on his machine ?

**Comment by notti** [comment]
It is also possible to use winpcap.
If you want packet capture, the only supported way so far is libpcap (via winpcap or npcap).

As far as I know, it is also possible to open raw sockets on windows via winsock, but then again you need a raw socket provider. I only know winpcap or npcap that provide that (I don't have much windows experience). As far as I know there is also another api native in newer windows versions, with which one can read packets (but not send), but this one is not supported by gopacket.

**Comment by JulienTant** [comment]
Hi

I sorry I didn't updated this. I finally built something in c# using raw sockets, and it looks like nothing is required on the host machine. Thank you !
