### ISSUE TITLE
cross compile from windows to linux failed

### ISSUE THREAD

**Issue by hujun-open** [google/gopacket#618]
I try cross compile from windows to linux, but it failed with following error (and I have no problem to compile an windows exe):
I wonder what do I miss here?
```
$ set GOARCH=amd64
$ set GOOS=linux
$ go build -v
github.com/google/gopacket/pcap
# github.com/google/gopacket/pcap
C:\Users\<removed>\go\src\github.com\google\gopacket\pcap\pcap.go:30:22: undefined: pcapErrorNotActivated
C:\Users\<removed>\go\src\github.com\google\gopacket\pcap\pcap.go:52:17: undefined: pcapTPtr
C:\Users\<removed>\go\src\github.com\google\gopacket\pcap\pcap.go:64:10: undefined: pcapPkthdr
```
* Go version:  go1.11.5 windows/amd64
* pcap.Version(): WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

here is a minimal example could cause this issue:
```
package main

import (
	"fmt"

	"github.com/google/gopacket/pcap"
)

func main() {
	fmt.Println(pcap.Version())
}
```

**Comment by notti** [comment]
The problem with this is, that pcap uses cgo on linux (there is no alternative on linux) for calling into libpcap. For cross compilation one would need a C-toolchain that can output linux binaries on windows, and libpcap for linux installed. I'm not sure that's possible to achieve.
Simplest solution would be to use a linuxvm or a linux container for this.

**Comment by hujun-open** [comment]
Thanks;
so I think  another workaround is using windows 10 WSL (Windows Subsystem for Linux) to build linux executable

**Comment by dylanpoe** [comment]
Have you solved your issues now ?
I have encountered the same error on my ubuntu 18.04 while I want to do the same cross compile
.....

**Comment by hujun-open** [comment]
> 
> 
> Have you solved your issues now ?
> I have encountered the same error on my ubuntu 18.04 while I want to do the same cross compile
> .....

no, I didn't; what I end-up doing is using WSL
