### ISSUE TITLE
tcpassembly page cache accounting bug

### ISSUE THREAD

**Issue by david415** [google/gopacket#62]
Dear Graeme,

If I understand correctly, there is a bug in your otherwise very nicely crafted tcpassembly; or I am again mistaken =-|

This page insertion doesn't always insert one page. It is incorrect to always increment by one here :
https://github.com/google/gopacket/blob/master/tcpassembly/assembly.go#L705

conn.pages is tracking pages per connection used... and here it's decremented. This part works fine:
https://github.com/google/gopacket/blob/master/tcpassembly/assembly.go#L763

**Comment by gconnell** [comment]
Ah, that sounds quite right... a single TCP packet can create > 1 pages if
its size is larger than the page size.  I'll get a fix out for this right
away :)

**Comment by gconnell** [comment]
Fix pushed @
https://github.com/google/gopacket/commit/2b92a1effab6f201b6035a66eec5717dd832cc59

Looking through, I'm pretty sure the original bug shouldn't have affected
correctness.  It did, however, affect when we flushed old connections with
too many pages.

**Comment by david415** [comment]
Your fix is precisely what I had in mind.

Agreed. It would have operated correctly, but it would not have enforced MaxBufferedPagesPerConnection, this might cause MaxBufferedPagesTotal to be reached more often if it was also set. If MaxBufferedPagesTotal was not set but MaxBufferedPagesPerConnection was then this bug could cause a lot more page cache consumption then the user expects. Of course as you point out... the page cache uage would still be time bounded if the calling party called FlushOlderThan.
