### ISSUE TITLE
gopacket linux undefined: pcapErrorNotActivated . Windows has no problem

### ISSUE THREAD

**Issue by hilisecs** [google/gopacket#629]
root@ubuntu:~/processNet/processNet# go run testversion.go 
# github.com/google/gopacket/pcap
/home/go/src/github.com/google/gopacket/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
/home/go/src/github.com/google/gopacket/pcap/pcap.go:52:17: undefined: pcapTPtr
/home/go/src/github.com/google/gopacket/pcap/pcap.go:64:10: undefined: pcapPkthdr

`package main

import (
        "fmt"

        "github.com/google/gopacket/pcap"
)

func main() {
        fmt.Println(pcap.Version())
}`

Already installed libpcap and c test available
What is the reason？

**Comment by notti** [comment]
Did you install libpcap-dev?

**Comment by hilisecs** [comment]
> Did you install libpcap-dev?

yes,    libpcap-dev is already the newest version (1.7.4-2).

This c code test is no problem
```
#include <stdio.h>
#include <pcap.h>

int main(int argc, char **argv) {
    char *device; /* Name of device (e.g. eth0, wlan0) */
    char error_buffer[PCAP_ERRBUF_SIZE]; /* Size defined in pcap.h */

    /* Find a device */
    device = pcap_lookupdev(error_buffer);
    if (device == NULL) {
        printf("Error finding device: %s\n", error_buffer);
        return 1;
    }

    printf("Network device found: %s\n", device);
    return 0;
}```

**Comment by notti** [comment]
Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)

**Comment by somnusx** [comment]
> Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)

Thanks, I found the reason, the environmental problem of go

**Comment by notti** [comment]
> > Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)
> 
> Thanks, I found the reason, the environmental problem of go

Did you change nicknames from hilisecs to somnusx?

**Comment by hilisecs** [comment]
> > > Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)
> > 
> > 
> > Thanks, I found the reason, the environmental problem of go
> 
> Did you change nicknames from hilisecs to somnusx?

Yes, these two are my account

**Comment by notti** [comment]
So we can close this.

**Comment by ljy296566** [comment]
> 
> 
> > Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)
> 
> Thanks, I found the reason, the environmental problem of go

I encountered the same problem, how can I solve it ?
<pre>
zxcasd@ubuntu:~/GoProjects/http$ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build --ldflags "-L ./libpcap-$PCAPV -linkmode external -extldflags \"-static\"" -a -o main
# github.com/google/gopacket/pcap
../../go/src/github.com/google/gopacket/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
../../go/src/github.com/google/gopacket/pcap/pcap.go:52:17: undefined: pcapTPtr
../../go/src/github.com/google/gopacket/pcap/pcap.go:64:10: undefined: pcapPkthdr
</pre>

**Comment by dylanpoe** [comment]
Hello, I got this same error , when I  want to cross compile an binary for arm7 for  Raspberry pi
my go is 1.13.5 
~/tcpdump/src/github.com/dylanpoe/tcpdump# GOOS=linux  GOARCH=arm64  GOARM=7  go build  main.go
# github.com/google/gopacket/pcap
../../google/gopacket/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
../../google/gopacket/pcap/pcap.go:52:17: undefined: pcapTPtr
../../google/gopacket/pcap/pcap.go:64:10: undefined: pcapPkthdr

**Comment by zxeoc** [comment]
I got the same errors. I don't know how @hilisecs solved it. I tried several ways. I found if I run "go build -i", I got something like "go build net: copying /home/zx/.cache/go-build/27/27773115f5636e1f6e9c44745b44f6bee029961b9b402d18d3f5da52c3fd1ddd-d: open /usr/lib/go/pkg/linux_amd64/net.a: permission denied"(go build without "-i" report "undefined" errors like others got, and /home/zx/.cache/go-build is my $GOCACHE). And I found my OS account has no permission to read or write the package in $GOPATH/pkg/mod/github.com/google/gopacket@v1.1.17. But trying to chmod the net.a file or the package doesn't solve the problem. Finally, I had to "sudo go build" my project and run it with sudo too, but at least it works.

**Comment by kureshu** [comment]
I m also facing the same same us, can some body brief the same for the solution.

**Comment by spoulson** [comment]
I fixed this issue by setting `CGO_ENABLED=1`.

**Comment by integrii** [comment]
For me, `CGO_ENABLED=1` was important, but I also needed to remove `GOARCH=amd64`.

**Comment by maggie0002** [comment]
A combination of CGO_ENABLED=1 and install the `libpcap-dev` package on linux based systems did the trick for me allowing building for windows, linux and Mac; arm and amd archs.

**Comment by hktalent** [comment]
@spoulson 
@integrii 
> I fixed this issue by setting `CGO_ENABLED=1`.

If so, you'll get new errors when you run
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./xxxx)

**Comment by lbq972149981** [comment]
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gor_linux

../../vendor/github.com/google/gopacket/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
../../vendor/github.com/google/gopacket/pcap/pcap.go:52:17: undefined: pcapTPtr
../../vendor/github.com/google/gopacket/pcap/pcap.go:64:10: undefined: pcapPkthdr

How can this situation be resolved

**Comment by GuardianRain** [comment]
> > Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)
> 
> Thanks, I found the reason, the environmental problem of go

So, where is the problem? I got the same trouble. How to fix it?

**Comment by GuardianRain** [comment]
> > > Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)
> > 
> > 
> > Thanks, I found the reason, the environmental problem of go
> 
> So, where is the problem? I got the same trouble. How to fix it?

I've already solved this problem. It seems that we shoud build the executable file in the plantform which we want the program to run. Build on windows for windows executable file, and linux for linux.
And, I have tried that the binary file built on amd64 linux can not run in arm linux OS.

**Comment by zxeoc** [comment]
> > > > Hmm this looks strange. Is there maybe some mixup with your go environments? (errors point to /home/go - but your command line says you ran go as root?)
> > > 
> > > 
> > > Thanks, I found the reason, the environmental problem of go
> > 
> > 
> > So, where is the problem? I got the same trouble. How to fix it?
> 
> I've already solved this problem. It seems that we shoud build the executable file in the platform which we want the program to run. Build on windows for windows executable file, and linux for linux. And, I have tried that the binary file built on amd64 linux can not run in arm linux OS.

Nope. I built and ran it both on the amd64 linux.

**Comment by lopz** [comment]
this fix the issue:
`sudo apt install  libpcap-dev gcc`

**Comment by jorgegomzar** [comment]
Hi, I encountered the exact same issue in a Docker container using golang 1.23.2.
@hilisecs @somnusx could you please be so kind to share how you manage to solve this issue?

**Comment by nangongchengfeng** [comment]
> 这修复了这个问题： `sudo apt install libpcap-dev gcc`

[root@ownit ecs_exporter]# go build main.go 
# github.com/google/gopacket/pcap
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:52:17: undefined: pcapTPtr
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:64:10: undefined: pcapPkthdr
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:103:6: undefined: pcapBpfProgram
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:110:7: undefined: pcapPkthdr
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:268:33: undefined: pcapErrorActivated
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:269:33: undefined: pcapWarningPromisc
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:270:33: undefined: pcapErrorNoSuchDevice
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:271:33: undefined: pcapErrorDenied
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:748:14: undefined: pcapTPtr
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:271:33: too many errors
[root@ownit ecs_exporter]# sudo  go build main.go 
sudo: go: command not found
[root@ownit ecs_exporter]# CGO_ENABLED=1
[root@ownit ecs_exporter]# sudo /usr/local/go/bin/go build main.go
sudo: /usr/local/go/bin/go: command not found
[root@ownit ecs_exporter]# sudo -E go build main.go
sudo: go: command not found



环境：Centos 7
Go版本：go version go1.23.2 linux/amd64
安装两个程序解析问题
[root@ownit ecs_exporter]# sudo yum install libpcap-devel gcc
