### ISSUE TITLE
How can I decode remote pcap

### ISSUE THREAD

**Issue by Juniorlimaivd** [google/gopacket#630]
Hello everyone, 

I'm redirecting traffic from a router with tcpdump to a connection, and i was able to read this stream with wireshark and show the packets with these commands:

In the router:
$ tcpdump -w - | netcat IP PORT

In the remote computer:
$ netcat -l IP PORT | wireshark -k -i - & 

I was wondering if I can do with gopacket a program that can decode pcap packets from a tcp connection, just as wireshark does. 

Thanks in advance.

**Comment by notti** [comment]
You could try to `pcap.OpenOfflineFile(os.Stdin)` to achieve the wireshark line (read pcap from stdin). Same could maybe work with the file handle returned from https://golang.org/pkg/net/#TCPConn.File

**Comment by Juniorlimaivd** [comment]
Thank you! The TCPConn.File() is exactly what I am looking for. Will close this issue now.
