### ISSUE TITLE
SIP with NewDecodingLayerParser()

### ISSUE THREAD

**Issue by Sergey-Zorin** [google/gopacket#637]
Why layers.SIP does not implement DecodingLayer interface?

I try this code
```
var sip layers.SIP
parser := gopacket.NewDecodingLayerParser(layers.LayerTypeEthernet, &eth, &ip4, &udp, &sip)
```
and get an error
```
cannot use &sip (type *layers.SIP) as type gopacket.DecodingLayer in argument to gopacket.NewDecodingLayerParser:
	*layers.SIP does not implement gopacket.DecodingLayer (missing CanDecode method)
```

Maybe author just forgot to write CanDecode method?

**Comment by gconnell** [comment]
We accept any submissions for new layers, including those that just implement the Layer interface and not the DecodingLayer interface.  For those that don't have a DecodingLayer interface, we also accept pull requests to add them :)
