### ISSUE TITLE
Panic encoding name in dns.go

### ISSUE THREAD

**Issue by bmeadors** [google/gopacket#638]
A panic happens while trying to serialize a DNS packet having authority records where the Name field is empty (<Root>).

The issue seems to be that the computeSize function used to determine the needed size of the buffer handles these empty Name fields slightly different than the encode function used to write data to said allocated buffer.  This causes the write offset to incorrectly grow by 1 byte for each authority record written and ends up causing the index out of range panic below.

panic: runtime error: index out of range

goroutine 15 [running]:
github.com/google/gopacket/layers.encodeName(0xc0001a45a0, 0x12, 0x60, 0xc0001aa000, 0x2a7, 0x2a7, 0x29f, 0x295)
	/root/go/src/github.com/google/gopacket/layers/dns.go:724 +0xe8
github.com/google/gopacket/layers.(*DNSResourceRecord).encode(0xc0000cd940, 0xc0001aa000, 0x2a7, 0x2a7, 0x294, 0x1, 0x20, 0x0, 0x0)
	/root/go/src/github.com/google/gopacket/layers/dns.go:754 +0x8dc
github.com/google/gopacket/layers.(*DNS).SerializeTo(0xc000142780, 0x9cc500, 0xc0000871d0, 0xc000030001, 0x40da68, 0x50)
	/root/go/src/github.com/google/gopacket/layers/dns.go:506 +0x5d5
github.com/google/gopacket.SerializeLayers(0x9cc500, 0xc0000871d0, 0x1, 0xc000049f90, 0x1, 0x1, 0x0, 0x0)
	/root/go/src/github.com/google/gopacket/writer.go:210 +0xcd
main.(*DnsContext).Run.func1.2(0xc0000224e0, 0xc000010090)

**Comment by notti** [comment]
Fixed by #638
