### ISSUE TITLE
gopacket does not build on openbsd

### ISSUE THREAD

**Issue by mischief** [google/gopacket#64]
```
0:mischief@thx1138:~/go/src/github.com/david415/HoneyBadger/cmd/honeyBadger$ go install
# github.com/google/gopacket/pcap
error: 'pcap_free_datalinks' undeclared (first use in this function)
error: 'pcap_offline_filter' undeclared (first use in this function)
```

this is OpenBSD 5.6, with the system libpcap.

**Comment by gconnell** [comment]
Do you happen to know which libpcap version is installed?

**Comment by mischief** [comment]
sorry, no, i can't tell myself. but i also tried on openbsd 5.7.

here's the header file. http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libpcap/pcap.h?only_with_tag=OPENBSD_5_7

i also attempted to link gopacket against a locally compiled version of pcap, but rather than compiler errors of undeclared functions, i got linker errors.

```
1:mischief@thx1138:~/go/src/github.com/david415/HoneyBadger/cmd/honeyBadger$ CGO_CFLAGS="-I$PCAP_PATH/include" CGO_LDFLAGS="-L$PCAP_PATH/lib" go build -x
WORK=/tmp/go-build313270947
mkdir -p $WORK/github.com/google/gopacket/pcap/_obj/
mkdir -p $WORK/github.com/google/gopacket/
cd /home/mischief/go/src/github.com/google/gopacket/pcap
CGO_LDFLAGS="-L/home/mischief/local/lib" /usr/local/go/pkg/tool/openbsd_amd64/cgo -objdir $WORK/github.com/google/gopacket/pcap/_obj/ -- -I $WORK/github.com/google/gopacket/pcap/_obj/ -I/home/mischief/local/include pcap.go
/usr/local/go/pkg/tool/openbsd_amd64/6c -F -V -w -trimpath $WORK -I $WORK/github.com/google/gopacket/pcap/_obj/ -I /usr/local/go/pkg/openbsd_amd64 -o $WORK/github.com/google/gopacket/pcap/_obj/_cgo_defun.6 -D GOOS_openbsd -D GOARCH_amd64 $
WORK/github.com/google/gopacket/pcap/_obj/_cgo_defun.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -print-libgcc-file-name
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/github.com/google/gopacket/pcap/_obj/ -I/home/mischief/local/include -o $WORK/github.com/google/gopacket/pcap/_obj/_cgo_main.o -c $WORK/github.com/google/gopacket/pcap/_obj/_cgo_main
.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/github.com/google/gopacket/pcap/_obj/ -I/home/mischief/local/include -o $WORK/github.com/google/gopacket/pcap/_obj/_cgo_export.o -c $WORK/github.com/google/gopacket/pcap/_obj/_cgo_ex
port.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/github.com/google/gopacket/pcap/_obj/ -I/home/mischief/local/include -o $WORK/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o -c $WORK/github.com/google/gopacket/pcap/_obj/pcap.cgo2
.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/github.com/google/gopacket/pcap/_obj/_cgo_.o $WORK/github.com/google/gopacket/pcap/_obj/_cgo_main.o $WORK/github.com/google/gopacket/pcap/_obj/_cgo_export.o $WORK/github.com/google/g
opacket/pcap/_obj/pcap.cgo2.o -L/home/mischief/local/lib
# github.com/google/gopacket/pcap
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0x73): In function `_cgo_c663009e3544_Cfunc_pcap_activate':
: undefined reference to `pcap_activate'
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0x9e): In function `_cgo_c663009e3544_Cfunc_pcap_can_set_rfmon':
: undefined reference to `pcap_can_set_rfmon'
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0xc9): In function `_cgo_c663009e3544_Cfunc_pcap_close':
: undefined reference to `pcap_close'
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0x112): In function `_cgo_c663009e3544_Cfunc_pcap_compile':
: undefined reference to `pcap_compile'
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0x145): In function `_cgo_c663009e3544_Cfunc_pcap_create':
: undefined reference to `pcap_create'
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0x172): In function `_cgo_c663009e3544_Cfunc_pcap_datalink':
: undefined reference to `pcap_datalink'
/tmp/go-build313270947/github.com/google/gopacket/pcap/_obj/pcap.cgo2.o(.text+0x19c): In function `_cgo_c663009e3544_Cfunc_pcap_datalink_val_to_description':
: undefined reference to `pcap_datalink_val_to_description'

... rest is elided ...
```

**Comment by gconnell** [comment]
Ah, I think that second issue is probably easier to fix...

Please try this change: https://github.com/google/gopacket/pull/66/files

Let me know if it works.  If it does, I can commit it to master.

**Comment by gconnell** [comment]
Merged into master.

**Comment by mischief** [comment]
ok, after some fuss, i got a git checkout of libpcap 1.6.2 to link, and @david415's honeyBadger is running on OpenBSD 5.6. thanks for the quick response. i'm unsure why the system libpcap doesn't work, i guess it could be old.

**Comment by gconnell** [comment]
Unfortunately, libpcap doesn't have a version defined, so you kind of have
to guess what's available vs. not based on #ifdefs (see
https://github.com/google/gopacket/blob/master/pcap/pcap.go#L26).  In
short, it's a real pain to try to support new features while still being
backwards incompatible.  If you do think of a clever ifdef check I can do
to handle your initial problem, I'd love to hear it :)

**Comment by mischief** [comment]
hm, rather unfortunate since the two functions that are missing are 'pcap_free_datalinks' and 'pcap_offline_filter', which are just small wrapper functions. i am tempted to write a pcap_openbsd.go file, that has copied definitions of these functions, with maybe a special build tag to indicate if one is using the openbsd system pcap or not. but, perhaps that's too hacky and a better idea is to just report these missing functions to openbsd team and deal with a custom libpcap for a while.

**Comment by gconnell** [comment]
Oh, actually free_datalinks/offline_filter is a particularly ornery case.
In libpcap 1.1.0, both were added, but no #define variables were.  So there
are no #ifdefs we can use to distinguish whether you're using libpcap
<1.1.0 vs >1.1.0.  In fact, I don't think we can be sure until 1.5.1 :(

**Comment by mischief** [comment]
alright, i'll poke tech@ and see what they will do about it. linking to a custom libpcap suffices for now. thanks @gconnell :-)
