### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by hdm** [google/gopacket#644]
Any chance a new release could be cut? I currently maintain a fork and would like to move back to upstream with the changes introduced since February 1st.  Thanks!

**Comment by notti** [comment]
There are a couple of pull-requests that I want to resolve before the next release, but I was busy the last couple of weeks with home improvement and trying to finish a paper. I'll try to get those resolved the during the upcoming week and then make a new release.

**Comment by notti** [comment]
@hdm  Any thoughts on #625 ?

**Comment by lebauce** [comment]
@notti I would also suggest this one : https://github.com/google/gopacket/pull/642

**Comment by notti** [comment]
Just issued the new release: https://github.com/google/gopacket/releases/tag/v1.1.17
