### ISSUE TITLE
DNS question encoding wrong length for roots

### ISSUE THREAD

**Issue by bmeadors** [google/gopacket#648]
DNS request packets with a question having an empty name (root server) are not being properly encoded.  The number of bytes consumed is incorrect in the encode function of the DNSQuestion struct.  It appears to only be off by a single byte but results in a malformed packet.  I recently submitted a PR for related issue #638 and failed to notice my change should have also been applied here as well.

**Comment by notti** [comment]
I lost track a bit - is #649 the fix for this?

**Comment by bmeadors** [comment]
Yes it is.  I should have made that more clear.

**Comment by notti** [comment]
Then we can close this issue.
