### ISSUE TITLE
How do I know which process the packet belongs to？

### ISSUE THREAD

**Issue by davidwudv** [google/gopacket#651]
Hello!
I want to capture packets for the specified process.
Is there any way I can do that?

**Comment by Galadros** [comment]
When you say "for the specified process," what do you mean?

**Comment by davidwudv** [comment]
> When you say "for the specified process," what do you mean?

Sorry, my english not well.
I mean, I want to capture packets for a process. But how do I know which process the packet belongs to？How do I get the PID associated with this packet？

**Comment by gconnell** [comment]
Hey, David,

Great question!  Unfortunately, there's not really a good answer for that
within GoPacket.  To do this, one needs to know which streams/sockets are
associated with a process, and that is very OS dependent.  In Linux, for
example, a 'netstat -pan' will get you some of that information.  Various
kernel hooks in Windows and Linux might do this, as might certain endpoint
detection systems that monitor for new socket creation for processes.  From
there, you'd have to associate a packet with a currently-in-use socket,
then map that back to a PID.  This is probably going to be a difficult task
if you want to do it generally, but if you can make some assumptions (this
process will be the only thing that ever uses this port, talks to this IP,
etc) then simple BPF filtering could do the trick.

  --Graeme

*From: *David Wu <notifications@github.com>
*Date: *Thu, May 9, 2019 at 8:30 PM
*To: *google/gopacket
*Cc: *Subscribed

When you say "for the specified process," what do you mean?

**Comment by davidwudv** [comment]
@gconnell 

Thanks your reply.
I will try it.
Thanks!
