### ISSUE TITLE
can't complie on golang 1.12.5

### ISSUE THREAD

**Issue by gujunyan** [google/gopacket#656]
i got these:

github.com/google/gopacket/pcap/pcap.go:203:7: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:488:13: identifier "_Ctype_struct_pcap_stat" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:533:49: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:556:10: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:589:41: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:661:66: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:674:19: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:801:34: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
src/github.com/google/gopacket/pcap/pcap.go:804:56: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo

why?

**Comment by yerden** [comment]
Please update gopacket to at least 0c245453. This should solve this.

**Comment by notti** [comment]
Yes, this should definitely solve the problem. Closing since this was already fixed.
