### ISSUE TITLE
go packet mips cross compile issue

### ISSUE THREAD

**Issue by eHeaven** [google/gopacket#662]
I make a packet sniffer program with gopacket,it can be compile and run well on Ubuntu 16.04 amd64 linux,but when I want build it for a mips linux device,an error occured(just like below). I googled some same issue,they say it's enviroment problem,but how to fix it,thank u if any help.

#!/usr/bin/env bash
export GOOS=linux;export GOARCH=mips;CGO_ENABLED=1;go build -ldflags "-static -s -w " main.go

# github.com/google/gopacket/pcap
../../google/gopacket/pcap/pcap.go:31:22: undefined: pcapErrorNotActivated
../../google/gopacket/pcap/pcap.go:53:17: undefined: pcapTPtr
../../google/gopacket/pcap/pcap.go:65:10: undefined: pcapPkthdr

-----------------------------------------------------------------------------------------------------------
Here is another test I use xgo,xgo also failed. does anyone met this problem?

john@ubuntu:~/go/src/github.com/karalabe/xgo$ sudo ./xgo --targets linux/mips github.com/bettercap/bettercap
Checking docker installation...
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:18:36 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:53:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/bettercap/bettercap...
Fetching main repository github.com/bettercap/bettercap...
github.com/bettercap/bettercap (download)
github.com/bettercap/recording (download)
github.com/evilsocket/islazy (download)
github.com/kr/binarydist (download)
Compiling for linux/mips...
# github.com/bettercap/bettercap/vendor/github.com/google/gopacket/pcap
vendor/github.com/google/gopacket/pcap/pcap_unix.go:34:18: fatal error: pcap.h: No such file or directory
compilation terminated.
# pkg-config --cflags  -- libusb-1.0
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
pkg-config: exit status 1
2019/06/05 20:16:22 Failed to cross compile package: exit status 2.

**Comment by notti** [comment]
The problem is this line here: vendor/github.com/google/gopacket/pcap/pcap_unix.go:34:18: fatal error: pcap.h: No such file or directory

gopacket/pcap needs libpcap -> you must have a cross compiled libpcap available. Some pointers on how to achieve this are in #100

**Comment by eHeaven** [comment]
Thank u,I got the point.that means I must cross compile the libpcap first and config the ENV path.
