### ISSUE TITLE
Go 1.12.5: "cgo argument has go pointer to go pointer" in BPF.Matches

### ISSUE THREAD

**Issue by adderou** [google/gopacket#664]
Hello, I'm having a problem with the method `BPF.matches` on Go 1.12.5 and the latest version of this library. 

When I use that method, the program panics with the message _cgo argument has go pointer to go pointer_ if `GODEBUG` is defined with `cgocheck=1`. 

It's important to note that a few months ago, I had no problems with the same method (I was using gopacket 1.1.17 and Go 1.11). 

The folowing code on my side is related to the panic:

```go
        // f is a gzipped pcap. I think this is not related to the problem, because it worked on Go 1.11
	reader, err := pcapgo.NewReader(f)
	if err != nil {
		msg := fmt.Sprintf("Couldn't open reader for file %s\n", f.Name())
		logs.Log.Error(msg)
		return err
	}

	data, ci, err := reader.ReadPacketData()
	if err != nil {
		msg := fmt.Sprintf("Couldn't read first packet from file %s\n", f.Name())
		logs.Log.Error(msg)
		return err
	}

	filter := conf.BPFFilter
	bpfi, err := pcap.NewBPF(reader.LinkType(), ci.CaptureLength, filter)
	if err != nil {
		msg := fmt.Sprintf("Couldn't make BPFFilter for file %s\n", f.Name())
		logs.Log.Error(msg)
		return err
	}

	if err != nil {
		msg := fmt.Sprintf("Couldn't set lastReadFile in config for file %s\n", f.Name())
		logs.Log.Error(msg)
	}

	packetSource := gopacket.NewPacketSource(reader, reader.LinkType())

	packet := gopacket.NewPacket(data, reader.LinkType(), gopacket.Default)
	m := packet.Metadata()
	m.CaptureInfo = ci
	m.Truncated = m.Truncated || ci.CaptureLength < ci.Length

	err = packetsSeen.ProcessPacket(packet)
	if err != nil {
		msg := fmt.Sprintf("Couldn't process first packet from file %s\n", f.Name())
		logs.Log.Error(msg)
		return err
	}

	for packet := range packetSource.Packets() {
		ci = packet.Metadata().CaptureInfo
		data = packet.Data()
		if len(data) == 0 {
			msg := fmt.Sprintf("Packet Data from file %s is empty\n", f.Name())
			logs.Log.Error(msg)
			return err
		}
		if bpfi.Matches(ci, data) { // The panic raises here
			err = packetsSeen.ProcessPacket(packet)
			if err != nil {
				msg := fmt.Sprintf("Couldn't process packet from file %s\n", f.Name())
				logs.Log.Error(msg)
				return err
			}
		}
	}
```

It seems that his issue is similar to #164. So I thought it is somehow related to the binding between the Go and C functions.  

I tried to fix it [in a fork I made] (https://github.com/adderou/gopacket) (modifying the `pcapOfflineFilter` method and its `pcap_offline_filter_escaping` C counterpart defined in `pcap/pcap_unix.go`) and it worked for my case, but I'm not so experienced on this libraries, so I would appreciate if someone else with more experience could check the problem and/or my solution. If it is correct, I could make a pull request.

Thanks in advance!

**Comment by notti** [comment]
> When I use that method, the program panics with the message _cgo argument has go pointer to go pointer_ if `GODEBUG` is defined with `cgocheck=1`.

According to the documentation `cgocheck=1` is the default value. So setting it to 1 should not change anything.

```
		if bpfi.Matches(ci, data) { // The panic raises here
```

I tried your code with `go version go1.12.5 linux/amd64` and neither with `cgocheck=1` nor `cgocheck=2` a panic happens (and this actually shouldn't happen here, since the contents of b.bpf come from C-land).

So there must be something different between our two systems that causes this. Which environment are you on?

**Comment by adderou** [comment]
Hi, thanks for answering.

You are right: the default configuration is `cgocheck=1`

I tested this on two different 64 bit Arch Linux systems, all updated with the latest packages and using `go mod` as dependency manager. I also confirmed that the version of the library I'm using is 1.1.17.

 In both situations I received this panic:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 11 [running]:
github.com/google/gopacket/pcap.(*BPF).pcapOfflineFilter.func1(0xc000398040, 0xc000398060, 0xc000466180, 0xc000180101)
        <my-gopath>/pkg/mod/github.com/google/gopacket@v1.1.17/pcap/pcap_unix.go:351 +0x6b
github.com/google/gopacket/pcap.(*BPF).pcapOfflineFilter(0xc000398040, 0x2293ab58, 0xed4918ec1, 0x0, 0x3c, 0x3c, 0x0, 0x0, 0x0, 0x0, ...)
      <my-gopath>/pkg/mod/github.com/google/gopacket@v1.1.17/pcap/pcap_unix.go:351 +0xc8
github.com/google/gopacket/pcap.(*BPF).Matches(...)
     <my-gopath>/pkg/mod/github.com/google/gopacket@v1.1.17/pcap/pcap.go:572
<my-package>.readFromCompressedFile(0xc0001d2000, 0xc0000e98b0, 0xc0000e9760, 0x1) // From here the stack points to my code
        <my-package>/functions.go:72 +0x4f6
<my-package>worker.func1(0xc000125300, 0xc0000e9dd8, 0xcb7900, 0xc0000c12c0, 0xc000124600, 0x0, 0x0, 0x1747180, 0x0, 0x0, ...)
       <my-package>/worker.go:42 +0x3e0
<my-package>.worker(0xc0002a01e0, 0xc0001d8080, 0xc00028ade0, 0xcb7900, 0xc0000c12c0, 0xc000124600, 0x0, 0x0, 0x1747180, 0x0, ...)
       <my-package>/worker.go:62 +0x163
created by <my-package>.createWorkerPool
        <my-package>/worker.go:77 +0x1f4
panic: runtime error: cgo argument has Go pointer to Go pointer
```

The name of my methods suggests that I am running this in many goroutines. This is true most of the time, but I also tried running it with only one goroutine and it still happens.

However, when I used my forked version, the panic disappeared.

I will try to run this in another environment. If I can replicate the problem in other distros (like Ubuntu or CentOS). If I can make it work, I'll comment with more information.

Thanks for the help!

**Comment by notti** [comment]
> I tested this on two different 64 bit Arch Linux systems, all updated with the latest packages and using `go mod` as dependency manager. I also confirmed that the version of the library I'm using is 1.1.17.

Oh I'm also on 64 bit Arch Linux.

> The name of my methods suggests that I am running this in many goroutines. This is true most of the time, but I also tried running it with only one goroutine and it still happens.

Ok so differences now:
 - I didn't use go.mod
 - I used a very short pcap file
 - I didn't use any goroutines

> However, when I used my forked version, the panic disappeared.

Your forked version "hides" everything from go by converting to `uintptr`, so I suspect this helps a bit, but I want to find out the underlying cause, since this might just fix a symptom.

I'll also have a look on the checking code that go does, because gopacket looks correct to me (unless I understood something wrong).

**Comment by notti** [comment]
@adderou can you try to
```go
	fmt.Printf("%p %#v\n", bpfi, bpfi)
```

this should look something like:
```
0xc00009e080 &pcap.BPF{orig:"here will be the filter", bpf:pcap.pcapBpfProgram{bf_len:0x1a, bf_insns:(*pcap._Ctype_struct_bpf_insn)(0x16d8e60)}, hdr:pcap.pcapPkthdr{ts:pcap._Ctype_struct_timeval{tv_sec:0, tv_usec:0}, caplen:0x0, len:0x0}}
```

and report the results?

**Comment by adderou** [comment]
@notti these are my results: 
```
0xc000446f80 &pcap.BPF{orig:"tcp", bpf:pcap.pcapBpfProgram{bf_len:0xc, bf_insns:(*pcap._Ctype_struct_bpf_insn)(0x7fd224002f80)}, hdr:pcap.pcapPkthdr{ts:pcap._Ctype_struct_timeval{tv_sec:0, tv_usec:0}, caplen:0x0, len:0x0}}
0xc0000160c0 &pcap.BPF{orig:"tcp", bpf:pcap.pcapBpfProgram{bf_len:0xc, bf_insns:(*pcap._Ctype_struct_bpf_insn)(0x7fd210002cd0)}, hdr:pcap.pcapPkthdr{ts:pcap._Ctype_struct_timeval{tv_sec:0, tv_usec:0}, caplen:0x0, len:0x0}}
0xc0005d8000 &pcap.BPF{orig:"tcp", bpf:pcap.pcapBpfProgram{bf_len:0xc, bf_insns:(*pcap._Ctype_struct_bpf_insn)(0x7fd2140030d0)}, hdr:pcap.pcapPkthdr{ts:pcap._Ctype_struct_timeval{tv_sec:0, tv_usec:0}, caplen:0x0, len:0x0}}
0xc000558040 &pcap.BPF{orig:"tcp", bpf:pcap.pcapBpfProgram{bf_len:0xc, bf_insns:(*pcap._Ctype_struct_bpf_insn)(0x7fd218002e20)}, hdr:pcap.pcapPkthdr{ts:pcap._Ctype_struct_timeval{tv_sec:0, tv_usec:0}, caplen:0x0, len:0x0}}
```

**Comment by notti** [comment]
Hmm those look good (0xc000XXXXXX look like pointers to go - which is right for bpfi, 0x7fd2XXXXXXXX look like pointer to C, which is correct for bf_insns).
So there must be something else going wrong. I tried several ways and couldn't replicate it.
Are there any other packages this uses? Can `bpfi` somehow be destroyed in between? Are the pointers still correct at the moment of the panic?

**Comment by adderou** [comment]
I think I found how to replicate the error. When I create the filter with a string literal, the code works. But when I load the variable from another place (like a config file or another custom variable, like I do on my code), it doesn't work.

Example, given this simple `main.go` file that works:
```go
package main

import (
	"fmt"
	"github.com/google/gopacket"
	"github.com/google/gopacket/pcap"
	"github.com/google/gopacket/pcapgo"
	"os"
)

func main() {
	filter := "tcp"
	pcapReader, err := os.Open("smallFlows.pcap") // Taken from https://tcpreplay.appneta.com/wiki/captures.html
	if err != nil {
		panic(err)
	}
	defer pcapReader.Close()
	reader, err := pcapgo.NewReader(pcapReader)
	if err != nil {
		panic(err)
	}

	data, ci, err := reader.ReadPacketData()
	if err != nil {
		panic(err)
	}
	packetSource := gopacket.NewPacketSource(reader, reader.LinkType())

	packet := gopacket.NewPacket(data, reader.LinkType(), gopacket.Default)
	m := packet.Metadata()
	m.CaptureInfo = ci
	m.Truncated = m.Truncated || ci.CaptureLength < ci.Length

	bpfi, err := pcap.NewBPF(reader.LinkType(), ci.CaptureLength, filter)
	if err != nil {
		panic(err)
	}
	for packet := range packetSource.Packets() {
		ci = packet.Metadata().CaptureInfo
		data = packet.Data()
		if len(data) == 0 {
			panic(err)
		}
		if bpfi.Matches(ci, data) {
			fmt.Printf("%+v", packet)
		}
	}
	return
}
```

If I change the "filter" definition on the first line of the main function to `filter := string([]byte("tcp"))`(trying to difficult to some optimization routine to notice that this value is always the same), I have the same panic I had on my code.

Hope this information helps!

**Comment by notti** [comment]
A that's it - I can reproduce it now. Thanks for looking into this.
I'll look into what causes this and try to come up with a fix.

**Comment by notti** [comment]
@adderou current master should work now. Thanks for helping track down the underlying bug and the patience.
