### ISSUE TITLE
Wrong usage of break statement

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/gopacket#680]
In line 278, the break statement means "break" `case block` instead of `loop block`. Therefore, since the variable `data` is never updated, it may cause an infinite loop.
You should add a label to the break statement.
https://github.com/google/gopacket/blob/da08d538c2bdf93ad103777b9a780b48d251258f/layers/tcp.go#L271-L279

**Comment by notti** [comment]
> In line 278, the break statement means "break" `case block` instead of `loop block`. Therefore, since the variable `data` is never updated, it may cause an infinite loop.
> You should add a label to the break statement.

Well actually data gets modified after the switch, still inside the loop -> this does not result in an infinite loop. However, this will decode multiple `end of option`.
