### ISSUE TITLE
golang crosscompile problem

### ISSUE THREAD

**Issue by superironbird** [google/gopacket#681]
I use gox to crosscompile gopackt program and I got a problem :
➜  bin #gox --osarch "linux/mips"
Number of parallel builds: 1

-->      linux/mips: _/root/go/bin

1 errors occurred:
--> linux/mips error: exit status 2
Stderr: # github.com/google/gopacket/pcap
../src/github.com/google/gopacket/pcap/pcap.go:52:17: undefined: pcapTPtr
../src/github.com/google/gopacket/pcap/pcap.go:64:10: undefined: pcapPkthdr

why?

**Comment by notti** [comment]
This happens if pcap.h is missing.

gopacket/pcap needs libpcap -> you must have a cross compiled libpcap available. Some pointers on how to achieve this are in #100
