### ISSUE TITLE
Is there any way to sniff on a unix socket?

### ISSUE THREAD

**Issue by c625473164** [google/gopacket#711]

**Comment by notti** [comment]
Short answer: No.

Long answer:

- You could mount a "Man in the Middle"-Attack: Rename the Unix socket, create a new one in it's place and then copy all the data from the new one to the original one. But for this you have to restart the communicating program
- Use something like `strace` on the program you want to observe and filter for everything that gets written or read to the fd belonging to the Unix socket in question.
