### ISSUE TITLE
criteria for reassembly delivering PDU from TCP data (PSH flag?)

### ISSUE THREAD

**Issue by rjm2718** [google/gopacket#746]
I'm working with reassembly, trying to understand when the assembler should deliver TCP data from the underlying streams to my application.  In addition to stream lifecycle events, and periodic flushing, what other criteria does reassembly use?

Specifically I'm looking at behavior for PSH and URG flags set in TCP packets.  I expect those flags to cause immediate delivery, but I'm not seeing it.  If the feature is there, please tell me.  I'm looking at tcpassembly.go and don't see any hint of it.

If the feature is not there and there's interest, I'll work on a patch for this.

best regards,
Ryan

**Comment by rjm2718** [comment]
The PSH flag should indeed push data immediately to the application.  I have created a PR [#755 ] for this.

There is a comment in tcpassembly.go:
`// TODO: push when Ack is seen ??`
but I cannot understand from my research if this should be the case.

**Comment by gconnell** [comment]
I believe things are working a little differently than that, but my understanding should be out of date.

reassembly should immediately give in-order data it has to users with no delay.  It only ever buffers data if it has received out-of-order packets, and in that case it buffers the packet until it gets packets which fill in the out-of-order holes in the stream, or until a FlushX method is called.

PSH should not, from my understanding, circumvent the out-of-order buffering/reassembly.

**Comment by rjm2718** [comment]
I see your point about only buffering out-of-order packets, so PSH flag set wouldn't change the behavior either way.  Receiving a PSH is not equivalent to calling a FlushX method, which is what I was originally thinking.
