### ISSUE TITLE
Pcap is not working on OpenVZ correctly 

### ISSUE THREAD

**Issue by pavel-odintsov** [google/gopacket#77]
Hello, Graeme! 

How are you?

I found new bug in your awesome library. Could you help me with it?

```bash
sudo ./find_pcap_devices 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43b188]

goroutine 1 [running]:
code.google.com/p/gopacket/pcap.sockaddr_to_IP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/sergey/golang/src/code.google.com/p/gopacket/pcap/pcap.go:539 +0x58
code.google.com/p/gopacket/pcap.findalladdresses(0x2be1430, 0xc2090d63f0, 0x0, 0x1)
    /home/sergey/golang/src/code.google.com/p/gopacket/pcap/pcap.go:525 +0xd5
code.google.com/p/gopacket/pcap.FindAllDevs(0xc2080c60b0, 0x3, 0x3, 0x0, 0x0)
    /home/sergey/golang/src/code.google.com/p/gopacket/pcap/pcap.go:511 +0x343
main.main()
    /home/sergey/golang/find_pcap_devices.go:9 +0x2a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

We are running gopacket inside of OpenVZ container which uses venet0 as main interface. 

```go
package main

import (
    "code.google.com/p/gopacket/pcap"
    "fmt"
)

func main() {
    all_devices, err := pcap.FindAllDevs()
    if err != nil {
        panic(err)
    }
    for _, device := range all_devices {
        fmt.Println(device.Name)
    }
}
```

**Comment by gconnell** [comment]
Hey, Pavel,

I can sure try :)

First off, would you mind switching from "code.google.com/p/gopacket" to "
github.com/google/gopacket"?  We moved the code about a month ago, so we
need to make sure you're at the most recent version.

Once you've done that, please run the check again and send me the output?
Thanks!

  --Graeme

**Comment by mrqwer88** [comment]
Hello!

With "github.com/google/gopacket/pcap" it have same problem.
On real hardware work good, but in OpenVZ container - 
```
sudo ./find_pcap_devices 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x452788]

goroutine 1 [running]:
github.com/google/gopacket/pcap.sockaddr_to_IP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sergey/golang/src/github.com/google/gopacket/pcap/pcap.go:540 +0x58
github.com/google/gopacket/pcap.findalladdresses(0x1f37430, 0xc2090d83f0, 0x0, 0x1)
	/home/sergey/golang/src/github.com/google/gopacket/pcap/pcap.go:526 +0xd5
github.com/google/gopacket/pcap.FindAllDevs(0xc2080c60b0, 0x3, 0x3, 0x0, 0x0)
	/home/sergey/golang/src/github.com/google/gopacket/pcap/pcap.go:512 +0x343
main.main()
	/home/sergey/golang/find_pcap_devices.go:10 +0x2a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by gconnell** [comment]
Could you patch in the following diff and rerun?:

--- pcap/pcap.go        2015-05-06 09:52:39.133588166 -0600
+++ pcap/pcap.go        2015-05-06 09:56:41.882089786 -0600
@@ -523,6 +523,7 @@
        for curaddr := addresses; curaddr != nil; curaddr =
(*_Ctype_struct_pcap_addr)(curaddr.next) {
                var a InterfaceAddress
                var err error
+               fmt.Printf("XXX ADDR: %#v PTR: %p\n", curaddr, curaddr.addr)
                if a.IP, err =
sockaddr_to_IP((*syscall.RawSockaddr)(unsafe.Pointer(curaddr.addr))); err
!= nil {
                        continue
                }

**Comment by mrqwer88** [comment]
Output with this patch -
```
sudo ./find_pcap_devices 
XXX ADDR: &pcap._Ctype_struct_pcap_addr{next:(*pcap._Ctype_struct_pcap_addr)(0x1f3c4d0), addr:(*pcap._Ctype_struct_sockaddr)(nil), netmask:(*pcap._Ctype_struct_sockaddr)(nil), broadaddr:(*pcap._Ctype_struct_sockaddr)(nil), dstaddr:(*pcap._Ctype_struct_sockaddr)(nil)} PTR: 0x0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x452a88]

goroutine 1 [running]:
github.com/google/gopacket/pcap.sockaddr_to_IP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sergey/golang/src/github.com/google/gopacket/pcap/pcap.go:542 +0x58
github.com/google/gopacket/pcap.findalladdresses(0x1f3c430, 0xc2090d23f0, 0x0, 0x1)
	/home/sergey/golang/src/github.com/google/gopacket/pcap/pcap.go:528 +0x1c2
github.com/google/gopacket/pcap.FindAllDevs(0xc2080c40b0, 0x3, 0x3, 0x0, 0x0)
	/home/sergey/golang/src/github.com/google/gopacket/pcap/pcap.go:513 +0x430
main.main()
	/home/sergey/golang/find_pcap_devices.go:10 +0x2a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by gconnell** [comment]
Okay, weird, it appears that sometimes we get back a linked list with
elements with nil addr.  The attached patch should fix... could you confirm
that it does?  If so, I'll send up a pull request to the master branch.

**Comment by mrqwer88** [comment]
Sorry, but I not see patch.

**Comment by gconnell** [comment]
--- pcap/pcap.go        2015-05-06 09:52:39.133588166 -0600
+++ pcap/pcap.go        2015-05-06 10:18:24.737503358 -0600
@@ -521,11 +521,21 @@
        // TODO - make it support more than IPv4 and IPv6?
        retval = make([]InterfaceAddress, 0, 1)
        for curaddr := addresses; curaddr != nil; curaddr =
(*_Ctype_struct_pcap_addr)(curaddr.next) {
+               // Strangely, it appears that in some cases, we get a pcap
address back from
+               // pcap_findalldevs with a nil .addr.  It appears that we
can skip over
+               // these.
+               if curaddr.addr == nil {
+                       continue
+               }
                var a InterfaceAddress
                var err error
                if a.IP, err =
sockaddr_to_IP((*syscall.RawSockaddr)(unsafe.Pointer(curaddr.addr))); err
!= nil {
                        continue
                }
+               // To be safe, we'll also check for netmask.
+               if curaddr.netmask == nil {
+                       continue
+               }
                if a.Netmask, err =
sockaddr_to_IP((*syscall.RawSockaddr)(unsafe.Pointer(curaddr.netmask)));
err != nil {
                        // If we got an IP address but we can't get a
netmask, just return the IP
                        // address.

**Comment by mrqwer88** [comment]
It work now!
sudo ./find_pcap_devices
venet0
any
lo

Thanks a lot!

**Comment by gconnell** [comment]
https://github.com/google/gopacket/pull/78

Please take a look at that pull and comment on it if it looks like it will
work for you.

Thanks for the report!

  --Graeme

**Comment by gconnell** [comment]
I believe this is now fixed.
