### ISSUE TITLE
Get the raw type and subtype values out of LayerType()

### ISSUE THREAD

**Issue by delta549** [google/gopacket#787]
The LayerType() function has a String() method but no way to extract the raw value type/subtype. Is there a way to get the raw type and subtype value from the packet without manually parsing the string it produces and converting that to the corresponding type? If not i feel this would improve the LayerType() and MainType() functions.

**Comment by trashbo4t** [comment]
It sounds like your calling LayerType on a type that is already a Layer interface. 

Instead of doing LayerType(), you can do LayerContents() or LayerPayload()

**Comment by delta549** [comment]
Cheers
