### ISSUE TITLE
afpacket v3 reads same packets over and over

### ISSUE THREAD

**Issue by fiorix** [google/gopacket#80]
Been trying to understand what's going on with afpacket when using TPacketVersion3, it reads the same packets over and over giving the impression that the position in the ring is messed up. Same code works well with both v1 and v2.

Has anyone experienced this?

**Comment by gconnell** [comment]
I haven't experienced it, but it's definitely possible.  The V3-specific
stuff is all in afpacket/header.go, specifically the next() method at
https://github.com/google/gopacket/blob/master/afpacket/header.go#L124.
Lines 130-134 in particular try to move the pointer to the next packet, and
I don't see anything obviously wrong there.  Maybe throw some Print
statements in there and see what the pointers are doing?

**Comment by gconnell** [comment]
Oh, could you also paste in the code you're using to read packets?  Are you
wrapping it in gopacket.NewPacketSource, or calling its methods directly?

**Comment by fiorix** [comment]
Actually I think this is because of writes to v3. Perhaps we should not allow writes there since it doesn't implement tx.

**Comment by gconnell** [comment]
Oh, this could definitely be the case.  I do no actual packet writing in
any of my projects, so I haven't tested that path particularly well.  I
think you're right, though... if writing fails for v3, we should just
disallow it for v3.

**Comment by raveinid** [comment]
Has this been resolved? We are seeing the same behavior using packetbeat. If it hasn't been resolved is there a timeline to resolution?

**Comment by fiorix** [comment]
¯\\_(ツ)_/¯
