### ISSUE TITLE
How to get the original packets after ip defragment or tcp reassembly?

### ISSUE THREAD

**Issue by leeefang** [google/gopacket#812]
Is there any way to get the original packets after ip defragment or tcp reassembly, instead of just returning the final result?

**Comment by gconnell** [comment]
The original packet is not kept as part of assembly, but it can be kept by the application that's passing the packets into the reassemblers.  gopacket/reassembly (newer than gopacket/tcpassembly) provides CaptureInfo as part of its reassembly interface.
