### ISSUE TITLE
PF_RING's ZeroCopyReadPacketData does not return control to the calling function

### ISSUE THREAD

**Issue by wontoniii** [google/gopacket#822]
Hello, I am developing an application in Go using PF_RING's zero copy driver (licensed). We have been having some issues with the ZeroCopyReadPacketData function as it never returns control to the caller function. We see that the driver is working, i.e. pfcount work without problems with the zc interfaces (zc:ifname@0), as well as showing stats (using the built in function https://github.com/google/gopacket/blob/master/pfring/pfring.go#L346). But we have no luck in getting ZeroCopyReadPacketData to work. The same exact code, minus using ZeroCopyReadPacketData, works like a charm.

Thank you very much for you help!

**Comment by gconnell** [comment]
Hmm, this is very confusing.  Both ReadPacketData and ZeroCopyReadPacketData call the exact same (blocking) codepath, `r.getNextBufPtrLocked(&ci)`.  I'm struggling to see how there'd be any difference in whether they'd block or not based on their calling.

**Comment by wontoniii** [comment]
Yes, it's quite puzzling for us, too. We have tested different possible combinations and I can confirm that the same exact setup works / does not work with / without zero copy. Our pipeline is actually shared and simply calls the different data read functions depending on the configuration. Here is the code of interest:

`// InitRing builds the pfring on the given device with the given snaplength
// TODO check that SetBPFFilter works with an empty filter
func initRing(device, filter string, snaplen uint32) (*pfring.Ring, error) {

	if ring, err := pfring.NewRing(device, snaplen, pfring.FlagPromisc); err != nil {
		return nil, err
	} else if err := ring.SetBPFFilter(filter); err != nil {
		return nil, err
	} else if err := ring.Enable(); err != nil {
		return nil, err
	} else {
		//TODO should we optimize this?
		ring.SetPollDuration(0) // default is 500ms - too slow for real-time
		ring.SetPollWatermark(0)
		ring.SetSocketMode(pfring.ReadOnly)
		return ring, nil
	}
}

func (ni *NetworkInterface) ReadPacketData() ([]byte, gopacket.CaptureInfo, error) {
	switch ni.HandleType {
	case HandleTypePFRing:
	if ni.ZeroCopy {
		return ni.Ring.ZeroCopyReadPacketData()
	} else {
		return ni.Ring.ReadPacketData()
	}
}
`

We do set the BPF filter (to all non DNS traffic). When using the device in zc mode (zc:ifname) it does not work while when running with the normal interface it doesn't have issues.

**Comment by wontoniii** [comment]
The exact call where it gets stuck (in zc mode) is this one: https://github.com/google/gopacket/blob/master/pfring/pfring.go#L153

**Comment by huzlee** [comment]
Maybe this is because this library chose "wait_for_incoming_packet" receive mode, that the program is blocked until a packet is available. Try to change the fifth parameter in the function
https://github.com/google/gopacket/blob/master/pfring/pfring.go#L41 to 0.

**Comment by wontoniii** [comment]
Sorry for the late reply. We uninstalled and installed all the libraries and it ended up working. I can't really tell what was the issue though.... 
Thanks a lot help! I will close the issue now.
