### ISSUE TITLE
compare layers.ICMPv6TypeCode

### ISSUE THREAD

**Issue by porjo** [google/gopacket#84]
I'd like to be able to do this:
```Go
	for _, layerType := range decoded {
		switch layerType {
		case layers.LayerTypeIPv6:
			switch icmp.TypeCode {
			case layers.ICMPv6TypeNeighborSolicitation:
				// do something
```
However comparing `icmp.TypeCode` with `layers.ICMPv6TypeNeighborSolicitation` doesn't work. In this case,   `icmp.TypeCode` == 34560 and `layers.ICMPv6TypeNeighborSolicitation` == 135 (bigendian vs littlendian)

**Comment by randstr** [comment]
Close?

**Comment by porjo** [comment]
@randstr works for me, thanks!
