### ISSUE TITLE
 SerializeOptions.ComputeChecksums not working?

### ISSUE THREAD

**Issue by porjo** [google/gopacket#86]
I've hit the same issue as reported in [this Stackoverflow question](http://stackoverflow.com/questions/29043283/pcap-go-using-raw-sockets-checksum-calculation):

Essentially, forwarding a packet between interfaces requires the checksum to be recalculated, however setting `SerializeOptions.ComputeChecksums=true` does not work as expected and the resulting packets are malformed.

My code is very similar to that listed in the post above, except I'm using IPv6 and forwarding ICMPv6:

```Go
	eth := n.eth
	eth.SrcMAC = iface.HardwareAddr
	ipv6 := n.ip6
	ipv6.SrcIP = linklocal
	buf := gopacket.NewSerializeBuffer()
	opts := gopacket.SerializeOptions{ComputeChecksums: true}

	gopacket.SerializeLayers(buf, opts, &eth, &ipv6, &n.icmp)

	handle.WritePacketData(buf.Bytes())
```

**Comment by gconnell** [comment]
Hmm, I expect we're incorrectly computing a checksum or just missing a checksum somewhere along the way.  I'll try to dig into this this week.

**Comment by david415** [comment]
Greetings. I'm curious to hear the results of further investigation into this bug... and I expect this bug is directly related to how gopacket implements the ipv6 checksum... we see here the preparatory step of creating the pseudo header for ipv4 and ipv6 here:

https://github.com/google/gopacket/blob/master/layers/tcpip.go#L24-L42

The checksum is computed here:
https://github.com/google/gopacket/blob/master/layers/tcpip.go#L44-L64

None of the code comments mention rfc2460... but maybe it's implemented correctly because someone was paying attention to that rfc when they wrote this code?

Here's a quote from rfc2460 that might be of interest when auditing these code bits:
```
The IPv6 version of ICMP [ICMPv6] includes the above pseudo-header in
   its checksum computation; this is a change from the IPv4 version of
   ICMP, which does not include a pseudo-header in its checksum.  The
   reason for the change is to protect ICMP from misdelivery or
   corruption of those fields of the IPv6 header on which it depends,
   which, unlike IPv4, are not covered by an internet-layer checksum.
   The Next Header field in the pseudo-header for ICMP contains the
   value 58, which identifies the IPv6 version of ICMP.
```

We can see that the ipv6 icmp uses the same machinery for computing checksums as the other protocols... 
https://github.com/google/gopacket/blob/master/layers/icmp6.go#L100

```If the IPv6 packet contains a Routing header, the Destination
         Address used in the pseudo-header is that of the final
         destination.  At the originating node, that address will be in
         the last element of the Routing header; at the recipient(s),
         that address will be in the Destination Address field of the
         IPv6 header.
```

**Comment by randstr** [comment]
Can you provide the complete example code and some IPv6 packet that, when decoded, modified and reserialized, produces malformed packets?

**Comment by porjo** [comment]
@randstr complete example code can be found [here](https://github.com/porjo/endyp/blob/proxy/proxy.go#L228). That is an NDP proxy in Go (based on ndppd) - it proxies neighbor solicitations and advertisements between 2 interfaces.

**Comment by randstr** [comment]
Thank you @porjo, that helps. I will look into it but meanwhile can you please elaborate on how you confirmed that the packets are malformed and furthermore that the problem is a bad checksum calculation?

**Comment by porjo** [comment]
@randstr I captured the resulting packets using Wireshark - it flags them as being malformed. With `ComputeChecksums=true` the resulting packets cannot even be decoded as ICMPv6 by Wireshark. With that options switched off, the packets look OK in Wireshark however it flags them as having an incorrect checksum. I've uploaded the PCAP files here:

http://demo.pace7.com/checksumFalse.cap
http://demo.pace7.com/checksumTrue.cap

**Comment by randstr** [comment]
@porjo Great, thanks. It seems to be a really interesting issue. :)

I will spin up some virtual machines to see if I can replicate the problem and figure it out.

**Comment by randstr** [comment]
@porjo There are only 8 bytes on the wire for checksumTrue.pcap. Did you notice that?

**Comment by porjo** [comment]
> Did you notice that?

Yes....The 2 packet captures were performed under identical conditions except one has `ComputeChecksums` switch on, and the other doesn't

**Comment by randstr** [comment]
@porjo Would it be possible to provide the capture for the ingress interface too?

**Comment by randstr** [comment]
@porjo BTW I think you'll want to add error checking to gopacket.SerializeLayers()...

**Comment by porjo** [comment]
> BTW I think you'll want to add error checking to gopacket.SerializeLayers()

Thanks, I've made a few adjustments now including this. Ingress interface capture is here:

http://demo.pace7.com/eth0.cap

**Comment by randstr** [comment]
I could be wrong but that capture makes me think you are not taking into account the ICMPv6 payload (target address and options for NS).

**Comment by porjo** [comment]
@randstr this is my first attempt doing this kind of thing, so it's very possible I've done something wrong in my code. AFAIK I am copying the original icmp layer unmodified into the write packet [here](https://github.com/porjo/endyp/blob/master/proxy.go#L229). If you can spot a problem with my code, I'd be glad to know about it. I take it you've been unable to reproduce the issue yourself? If so, what code have you used?

**Comment by randstr** [comment]
I haven't gotten around to it yet. Another idea is using the ingress capture you provided to try to come up with a failing test case (probably about as much work as setting up a proper testbed environment and likely to be more fruitful).

**Comment by randstr** [comment]
@porjo I usually prefer to work with packets instead of layers for decode-change-serialize but how about trying (line 190):

```Go
	parser := gopacket.NewDecodingLayerParser(layers.LayerTypeEthernet, &eth, &ip6, &icmp, &icmp_payload)
```

**Comment by porjo** [comment]
@randstr Thanks, that helped alot. I've made further changes to my code now which has stopped the malformed packets and also achieved working `ComputeChecksums`.

 I'm fairly confident now the problem I had is not a bug with Gopacket - just incorrect implementation on my part! I will close this issue now and reopen again later if necessary.

**Comment by randstr** [comment]
@porjo Glad I could help. Just one last note, consider whether that code will work with IPv6 extension headers or not.
