### ISSUE TITLE
FastHash Collision Rate High for Layer4 Flows

### ISSUE THREAD

**Issue by upsampled** [google/gopacket#860]
I am building a small analysis program to produce something like an annotated Wireshark "Follow TCP Stream" output by merging the two directional streams of a TCP conversation. My hope was that using the FashHash (Layer 3 and 4) output I could map the two directional flows together; however, I experienced a problem with my very small (three tcp stream) test pcap file. Two of the three TCP conversations had the same Fast Hash values, but used different ports:

* server port 7028 and client port 64717 result `a0d19934c49f0278`
* server port 7029 and client port 64718 result `a0d19934c49f0278`

I initially thought I did something wrong, so I wrote [test ](https://play.golang.org/p/MrTxDmFC6N_x)code that showed the collision

My goal in pointing this out is to:
* make sure the documentation mentions FastHash is at least not currently collision resistant with other Flow sets 
* propose that either FastHash is updated or a another hash method be added (PrettyFastHash, FastishHash, etc)  that is collision resistant.

**Comment by secmobi** [comment]
_disclaimer: I'm only a gopacket user like you, not the maintainer._ 

I think current doc has **implicitly** suggested this. In the project's general introduction on usages, it says and here I quote: 

> For load-balancing purposes, both Flow and Endpoint have FastHash() functions, which provide quick, non-cryptographic hashes of their contents.

And in [the function's description](https://pkg.go.dev/github.com/google/gopacket#Flow.FastHash) it mentioned similar idea again that: 

> FastHash provides a quick hashing function for a flow, useful if you'd like to split up flows by modulos or other load-balancing techniques.

That's been said, I believe a more **explicit** note would be necessary, to emphasize that it's improper to use the function's return values for session/flow's unique key purpose. 

On the second part of your suggestion on finding other collision resistant hash, I feel a paradox here: the hash shall be commutative (i.e., output the same hash for flow of A -> B and for flow B -> A therefore two flows in the same session will have the same hash values); however, a commutative hash won't be a cryptographic hash function due to the characteristic of h(A+B) == h(B+A).

**Comment by upsampled** [comment]
After digging into this more and writing a brute forcer, the (FNV+FNV) hash performs worse than expected for the Layer 4 order-independent, port-pair combinations. I am seeing approx 5.5K collisions for every combination. I believe this is mostly due to the single FNV hash function `fnvHash` performing poorly with small inputs. For example:

1. Given port 1 the hash is `8328707b4eb6e3a`
2. Given port 2 the hash is `8328607b4eb6c87`
3. Given port 3 the hash is `8328507b4eb6ad4`

It is pretty obvious that there is barely any change occurring. The next step `fnvHash(f.src[:f.slen]) + fnvHash(f.dst[:f.dlen])` does not remedy this issue and potentially makes it worse. 

There may be an easy solution for the majority of endpoints, as they have 32-bit or less addresses. You can get the same performance with **no collisions** by combining the addresses in an order independent way (smaller input gets lower bit, larger input gets higher bits):
```
//SaferFastHash non-collision hash generation for endpoints
//with less than 32 bits long
func (f Flow) SaferFastHash() (h uint64) {
	var a, b, src, dst uint64

	if f.slen == 2 && f.dlen == 2 {
		src = uint64(binary.BigEndian.Uint16(f.src[:f.slen]))
		dst = uint64(binary.BigEndian.Uint16(f.dst[:f.dlen]))
	} else if f.slen == 2 && f.dlen == 2 {
		src = uint64(binary.BigEndian.Uint32(f.src[:f.slen]))
		dst = uint64(binary.BigEndian.Uint32(f.dst[:f.dlen]))
	} else {
		return f.FastHash()
	}

	a = src<<32 + dst
	b = dst<<32 + src

	if a < b {
		return a
	}
	return b
}
```
* I did not use the f.typ because it can cause collisions in the IPv4 case and this can be taken into account separately 
```
goos: linux
goarch: amd64
pkg: github.com/google/gopacket
cpu: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
BenchmarkFlowFastHashShort-4            271140177                6.187 ns/op
BenchmarkFlowSafeFastHashShort-4        196695616                5.530 ns/op
PASS
ok      github.com/google/gopacket      5.011s
```

This satisfies the requirements of the FastHash function 
1. Hash(A,B) == Hash(B,A) 
2. Hash is type uint64 
3. Fast as possible

With the added perk of not having collisions.  
* Also @secmobi this is a non-cryptographic hash function because it is not a one-way function, it can be reversed. 

Given this, I recommend one of the following:
* Replace the FastHash function with something better suited for the most common input (address length <=32 ). Fallback to the original FastHash for longer addresses, such as IPv6 and MAC.
* Create a new function SmallFastHash that can used for optionally for Endpoints with 32-bit or less addresses.

**Comment by gconnell** [comment]
Hey, author here.  I'd be 100% happy to accept any replacement to the FastHash implementation that, as you've pointed out, is symmetric (A,B)=(B,A) and fast.  You're very right, it was in no way designed for collision resistance.

As you've already correctly pointed out, diffusion in the hash is quite bad (https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#Non-cryptographic_hash):

```
Diffusion – The ideal secure hash function is one in which each byte of input has an equally-complex
effect on every bit of the hash. In the FNV hash, the ones place (the rightmost bit) is always the XOR
of the rightmost bit of every input byte.
```

**Comment by upsampled** [comment]
@gconnell **Firstly**, thank you for your work. GoPacket is so much easier to work with than Wireshark dissectors. 

**Secondly**, are you OK with allowing Endpoint specific fast hash functions that would be registered in the `EndpointTypeMetadata` struct?

The hash I proposed handles the less than 32-bit address case, which just leaves addresses larger than that. We can keep on being address type independent (currently FNV+FNV) or we can allow an override for address type specific hashing. If we allow the override then the hashing function can leverage the entropy in the assignment of addresses of that type. 

The override fasthash function would then take the following behavior:
* If a custom fasthash function is registered, it is used. 
* If no function is registered and the endpoint addresses are less than or equal to 32 bytes then the fasthash function above is used.
* If no function is registered and the endpoint addresses are greater than 32 bytes then the FNV+FNV fasthash function is used.

### potential endpoint specfic fasthash functions 
* For MAC addresses, the last 4 bytes should be a very reliable way of hashing (3 byte for the link id and 1 byte for the vendor). It should even handle the Multicast case fairly well as the `C2` should be caught in the 1 vendor byte. 

* For IPv6, it looks like ordering the bytes by [entropy ](https://www.mesalab.cn/managercode/achievements/A%C2%A0high%C2%A0performance%C2%A0IPv6%C2%A0flow%C2%A0table%C2%A0lookup%C2%A0algorithm%C2%A0based%C2%A0on%C2%A0hash.pdf) and then using Von Neumann is a good approach. This might be improved if bytes 2 and 8 are higher in evaluation order to handle SLAAC, RA prefix advertisements and  EUI-64 cases.

**Comment by upsampled** [comment]
Ok, I have abandoned the ability to register custom Endpoint FastHash/FlowLabel functions. It is way too slow.

More fundamentally, the `Flow.FastHash` is right at the inline budget cost maximum (80), so any additional logic prevents it from being inline-d and induces a relatively huge performance hit (3x-4x slowdown). 
```
$go build -gcflags='-m=2' ./ 2>&1 | grep flows\.go | grep inlin | grep Fast
can inline Flow.FastHash with cost 80 as: method(Flow) func() uint64 { h = fnvHash(f.src[:f.slen]) + fnvHash(f.dst[:f.dlen]); h ^= uint64(f.typ); h *= fnvPrime; return  }
```

At this point I am looking into different FNV or Von Neumann hashing algorithms that can handle the low byte count addresses better. Another fast algorithm may not be collision free, but I should be able to at least improve the 8% collision rate for layer 4 port pairs.

**Comment by gconnell** [comment]
Hey, all, been talking about this with unsampled in the pull request, but wanted to get opinions from the rest of you:

**Comment by gconnell** [comment]
Oops, sorry, accidentally hit a button.  Didn't mean to close this out.

**Comment by upsampled** [comment]
After exploring collision-free alternatives, it is clear that FastHash is more tailored for Load-balancing which prefers high entropy in the least significant bits. IE: `jobs[f.FastHash() % SIZE] <- f`. 

Flow analysis and inspection prefers hashes that emphasizes uniqueness ( FastHash(A->B) != FastHash(C->D) ). IE: `conversations[f.FastHash]`

Given the need to inline the FastHash functions for speed, only one Alg can be used. For this reason it is better to stick with FNV as it handles any input, regardless of structure, for the intended load-balancing purpose.

**Comment by gconnell** [comment]
Hey, unsampled, just wanted to thank you a ton for your really in-depth analysis of this problem.  This issue will be a great reference for future discussions on the issue.
