### ISSUE TITLE
Add basic BSD-only BPF ethernet sniffer (PacketDataSource)

### ISSUE THREAD

**Issue by david415** [google/gopacket#87]
Dear gopacket developers,

If we add a BSD BPF ethernet sniffer (PacketDataSource) to gopacket then we'll be able to run our protocol analyzers on all the major BSD operating systems... not just Linux.

I recently wrote a very simple ethernet sniffer API implementing the PacketDataSource interface... It doesnt' support the BPF bytecode filtering but that could be added later. Right now it sniffs all of the packets.

Does this sound like a feature we could add to gopacket?

**Comment by gconnell** [comment]
Sure, that sounds great!  Feel free to drop me a pull request, and we can
start the review.

**Comment by david415** [comment]
OK... here's the rough draft:
https://github.com/google/gopacket/pull/88

looking forward to getting review so we can clean this code up.

Cheers

**Comment by david415** [comment]
The BSD BPF API has lots of options to set... but maybe we have enough of them for now?

https://golang.org/src/syscall/bpf_bsd.go
https://www.freebsd.org/cgi/man.cgi?bpf%284%29
