### ISSUE TITLE
no buildable Go source files in gopacket/afpacket

### ISSUE THREAD

**Issue by amlwwalker** [google/gopacket#96]
I am trying to build `https://github.com/bisrael8191/sniffer` and it says:

> no buildable Go source files in gopacket/afpacket

I have it included correctly, but as there is no main() in that package, i cannot build it. Whats the procedure here?

**Comment by mattes** [comment]
``go get -d github.com/google/gopacket/afpacket``

From the [docs](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies): 

> The -d flag instructs get to stop after downloading the packages; that is, it instructs get not to install the packages.

**Comment by gconnell** [comment]
https://github.com/google/gopacket/blob/master/afpacket/afpacket.go#L7

afpacket is a Linux kernel feature, so we don't bother to build anything if you're not building on a Linux machine.  What OS are you building on?

**Comment by notti** [comment]
The mentioned project directly depends on afpacket, and the error can only happen on non-linux (due to afpacket only supporting linux).
