### ISSUE TITLE
Reading PCAP Files question

### ISSUE THREAD

**Issue by mattes** [google/gopacket#97]
Hey! I don't think the returned channel from `packetSource.Packets()` is closed when the PCAP file reached io.EOF. Or am I doing something wrong? It iterates forever for me. Can someone help? :)

``` go
if handle, err := pcap.OpenOffline("/path/to/my/file"); err != nil {
  panic(err)
} else {
  packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
  for packet := range packetSource.Packets() {
    handlePacket(packet)  // Do something with a packet here.
  }
}
```

Source: https://godoc.org/code.google.com/p/gopacket/pcap#hdr-Reading_PCAP_Files

**Comment by notti** [comment]
Could not reproduce.
